### ISSUE TITLE
Crash on Forge Server while Applying Mixins for fox

### ISSUE THREAD

**Issue by HerobrineXia** [Virtuoel/Pehkui#119]
`[18:19:18] [main/DEBUG] [mixin/]: Mixing compat116plus.FoxEntityMateGoalMixin from pehkui.mixins.json into net.minecraft.entity.passive.FoxEntity$MateGoal
[18:19:18] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/entity/ai/goal/BreedGoal to metadata cache
[18:19:18] [main/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://minecraft/net/minecraft/entity/passive/FoxEntity.class got resource net/minecraft/entity/passive/FoxEntity.class true
[18:19:18] [main/TRACE] [mixin/]: Added class metadata for net/minecraft/entity/passive/FoxEntity to metadata cache
[18:19:18] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[18:19:18] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:98)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:95)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:92)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: Caused by: java.lang.reflect.InvocationTargetException
[18:19:18] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	... 7 more
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at net.minecraft.entity.EntityType.<clinit>(EntityType.java:178)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at net.minecraft.world.gen.feature.DungeonsFeature.<clinit>(DungeonsFeature.java:24)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at net.minecraft.world.gen.feature.Feature.<clinit>(Feature.java:37)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at net.minecraft.world.gen.feature.Features.<clinit>(SourceFile:92)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243672_e(WorldGenRegistries.java:39)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at net.minecraft.util.registry.WorldGenRegistries.lambda$static$8(WorldGenRegistries.java:89)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:41)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at net.minecraft.server.Main.main(Main.java:118)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	... 13 more
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method onBreed(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/world/server/ServerWorld;Lnet/minecraft/entity/passive/FoxEntity;)V in pehkui.mixins.json:compat116plus.FoxEntityMateGoalMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Pehkui-refmap.json
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[18:19:18] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	... 34 more
`
Crash while applying Mixins for fox.

**Comment by Virtuoel** [comment]
Fixed in 32b2c98343af20e09c849deb71957dbe365863cb
