### ISSUE TITLE
1.17 will not start with latest release

### ISSUE THREAD

**Issue by GraphicHealer** [Virtuoel/Pehkui#138]
I have your mod along with Immersive Portals, and it will not launch when Pehkui is in the mods folder. Once I remove it, it launches just fine. I don't know why it is doing this. Please help.

Log: 

15:37:14.801
launcher
main
Preparing to launch minecraft client for fabric-loader-0.11.3-1.17
15:37:16.322
launcher
main
Checking installations.
15:37:16.324
launcher
main
Minecraft client fabric-loader-0.11.3-1.17 is ready to start.
15:37:16.324
launcher
main
Starting!
15:37:17.285
launcher
main
Using default game log configuration client-1.12.xml (outputs XML)
15:37:17.949
FabricLoader
main
Loading for game Minecraft 1.17
15:37:18.296
Fabric|Loader
main
Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b4463d5, also found 0.3.0+a02b4463a0
 - Conflicting versions found for fabric-lifecycle-events-v1: used 1.4.4+a02b4463a0, also found 1.4.4+a02b4463d5
 - Conflicting versions found for fabric-command-api-v1: used 1.1.1+a02b4463a0, also found 1.1.1+a02b4463d5
 - Conflicting versions found for fabric-events-interaction-v0: used 0.4.8+a02b4463d5, also found 0.4.8+a02b4463a0
 - Conflicting versions found for fabric-resource-loader-v0: used 0.4.7+b7ab6121a0, also found 0.4.7+b7ab6121d5
 - Conflicting versions found for fabric-networking-api-v1: used 1.0.11+b7ab6121a0, also found 1.0.11+b7ab6121d5

15:37:18.299
Fabric|Loader
main
[FabricLoader] Loading 56 mods: fabric-renderer-api-v1@0.4.2+a02b4463d5, fabric-keybindings-v0@0.2.2+36b77c3ed5, fabricloader@0.11.3, fabric-structure-api-v1@1.1.10+be9da310d5, fabric-containers-v0@0.1.12+a02b4463d5, fabric-dimensions-v1@2.0.10+a02b4463d5, fabric-object-builder-api-v1@1.10.9+b7ab6121d5, pehkui@2.2.0+21w20a, java@16, fabric-game-rule-api-v1@1.0.6+a02b4463d5, fabric-api-base@0.3.0+a02b4463d5, fabric-rendering-data-attachment-v1@0.1.5+a02b4463d5, fabric-textures-v0@1.0.6+a02b4463d5, q_misc_util@0.2, fabric-rendering-fluids-v1@0.1.13+a02b4463d5, litematica@0.0.0-dev.20210603.144652, fabric-blockrenderlayer-v1@1.1.5+a02b4463d5, fabric-lifecycle-events-v1@1.4.4+a02b4463a0, fabric-renderer-registries-v1@3.2.0+a02b4463d5, immersive_portals@0.2, minihud@0.19.0-dev.20210607.133352, fabric-loot-tables-v1@1.0.4+a02b4463d5, fabric@0.34.9+1.17, carpet@1.4.40, fabric-particles-v1@0.2.4+a02b4463d5, fabric-networking-v0@0.3.2+92519afad5, fabric-api-lookup-api-v1@1.0.2+a02b4463d5, imm_ptl_core@0.2, fabric-networking-blockentity-v0@0.2.11+a02b4463d5, minecraft@1.17, fabric-screen-handler-api-v1@1.1.8+a02b4463d5, fabric-command-api-v1@1.1.1+a02b4463a0, fabric-screen-api-v1@1.0.3+b7ab6121d5, fabric-tool-attribute-api-v1@1.2.12+b7ab6121d5, fabric-renderer-indigo@0.4.8+a02b4463d5, fabric-crash-report-info-v1@0.1.5+be9da310d5, fabric-item-api-v1@1.2.4+a02b4463d5, fabric-events-interaction-v0@0.4.8+a02b4463d5, fabric-entity-events-v1@1.1.0+a02b4463d5, fabric-rendering-v0@1.1.2+92519afad5, fabric-key-binding-api-v1@1.0.4+a02b4463d5, fabric-rendering-v1@1.6.0+a02b4463d5, fabric-resource-loader-v0@0.4.7+b7ab6121a0, malilib@0.10.0+dev.22, fabric-content-registries-v0@0.2.2+a02b4463d5, fabric-tag-extensions-v0@1.1.4+a02b4463d5, worldedit@7.2.6-SNAPSHOT+5797-8609960, fabric-biome-api-v1@3.1.11+9e521e13d5, fabric-commands-v0@0.2.2+92519afad5, fabric-registry-sync-v0@0.7.9+a02b4463d5, fabric-mining-levels-v0@0.1.3+92519afad5, fabric-networking-api-v1@1.0.11+b7ab6121a0, fabric-events-lifecycle-v0@0.2.1+92519afad5, fabric-item-groups-v0@0.2.10+b7ab6121d5, fabric-models-v0@0.3.0+a02b4463d5, fabric-object-builders-v0@0.7.3+a02b4463d5
15:37:18.336
mixin
main
SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/<USER>/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT

15:37:18.441
mixin
main
The requested compatibility level JAVA_16 is higher than the level supported by the active subsystem 'Knot/Fabric' which supports JAVA_14. This is not a supported configuration and instability may occur.
15:37:18.442
mixin
main
Compatibility level set to JAVA_16
15:37:18.851
com.sk89q.worldedit.fabric.internal.MixinConfigPlugin
main
[carpet] detected, disabling UPDATE mixin com.sk89q.worldedit.fabric.mixin.MixinWorldChunkSetBlockHook
15:37:18.914
mixin
main
@Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value

15:37:18.965
mixin
main
@Mixin target net/minecraft/class_3898$class_3208 is public in imm_ptl.mixins.json:common.entity_sync.MixinEntityTracker and should be specified in value
15:37:19.084
mixin
main
@Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
15:37:19.217
mixin
main
Error loading class: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval)

15:37:20.160
launcher
main

Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_6396.handler$bjm001$fillSystemDetails(class_6396.java:1022)
	at net.minecraft.class_6396.<init>(class_6396.java:57)
	at net.minecraft.class_128.<init>(class_128.java:31)
	at net.minecraft.class_128.method_24305(class_128.java:273)
	at net.minecraft.client.main.Main.main(Main.java:137)
	... 7 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method onTickMovementGetVelocityProxy(Lnet/minecraft/class_243;)Lnet/minecraft/class_243; in pehkui.mixins.json:PlayerEntityMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Pehkui-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 18 more
15:37:20.160
monitor
Process Monitor
Process crashed with exit code 1

**Comment by Virtuoel** [comment]
Fixed in Pehkui 2.2.1.
