### ISSUE TITLE
[Bug]: Game crashes with reach weapons

### ISSUE THREAD

**Issue by SirResigmenduken** [Virtuoel/Pehkui#160]
### Minecraft version(s)

1.17.1

### Mod loader

Fabric

### Mod loader version

1.17.1

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

With weapons that have extended reach from medieval weapons, holding them and hitting F5 crashes the game. After some testing, removing this mod and repeating the steps doesn't cause a crash. Crash error says:

Error: java.lang.IllegalStateException: Pose stack not empty
Exit code: -1

### Full list of installed mods

	- amecsapi@1.1.5+mc21w16a
	- antiqueatlas@6.0.0-fabric-mc1.17.1
	- apoli@1.0.4
	- aqupdgrizzly@1.1.1
	- architectury@2.3.24
	- backslot@1.2.0
	- backslotaddon@1.0.5
	- bedspreads@1.4.0-1.17
	- calio@1.0.2
	- cardinal-components-base@3.0.0
	- cardinal-components-entity@3.0.0
	- charmonium@3.3.0
	- cloth-basic-math@0.5.1
	- cloth-config2@5.0.38
	- com_electronwill_night-config_core@3.6.2
	- com_electronwill_night-config_toml@3.6.2
	- com_moandjiezana_toml_toml4j@0.7.2
	- dynamicsoundfilters@1.2.0+1.17
	- earthtojavamobs@1.7.1+1.17
	- enchant_giver@1.1.0
	- fabric@0.37.2+1.17
	- fabric-api-base@0.3.0+a02b446318
	- fabric-api-lookup-api-v1@1.2.0+2b5c62d018
	- fabric-biome-api-v1@3.1.11+c345aea818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+a02b446318
	- fabric-content-registries-v0@0.2.4+2e8bd82f18
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.1.0+a02b446318
	- fabric-events-interaction-v0@0.4.9+a722d8c018
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+6cefd57718
	- fabric-item-api-v1@1.2.4+a02b446318
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+a02b446318
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-lifecycle-events-v1@1.4.4+a02b446318
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.13+2e8bd82f18
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+b7ab612118
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+5f02c96918
	- fabric-renderer-indigo@0.4.8+a02b446318
	- fabric-renderer-registries-v1@3.2.0+a02b446318
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446318
	- fabric-rendering-fluids-v1@0.1.13+a02b446318
	- fabric-rendering-v0@1.1.2+92519afa18
	- fabric-rendering-v1@1.7.0+2e8bd82f18
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+155f865c18
	- fabric-screen-handler-api-v1@1.1.8+a02b446318
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.1.4+a02b446318
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
	- fabric-transfer-api-v1@1.0.0+3fe3c3f518
	- fabricloader@0.11.6
	- fallflyinglib@3.0.0-beta.2
	- fallingleaves@1.7.3+1.17.1
	- fiber@0.23.0-2
	- healthoverlay@4.0.1
	- inmis@2.3.1-1.17
	- java@16
	- kanos_config@0.1.4+1.14.4-1.17.1
	- kirin@1.9.1
	- maybe-data@1.0.1-1.17
	- mcdw@3.3.5
	- medievalweapons@1.1.6
	- minecraft@1.17.1
	- moborigins@1.6.0
	- omega-config@1.0.4
	- origins@1.0.3
	- origins-classes@1.2.2
	- pehkui@2.3.0+1.14.4-1.17.1
	- pettable@1.2.0
	- playerabilitylib@1.3.0-nightly.1.17-rc1
	- presencefootsteps@r32-1.17-rc1
	- reach-entity-attributes@2.1.1
	- roughlyenoughitems@6.0.267-alpha
	- seasons@1.2.2-BETA+1.17
	- static-content@1.0.1-1.16.2
	- staticdata@1.1.2
	- torohealth@1.17.1-fabric-11
	- wolveswitharmor@1.6.0-1.17

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
Caused when hitting F5

<summary>Crash report output:</summary>

Game crashed because of a changed perspective with a reach weapon

<p>
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 8/10/21, 6:39 PM
Description: Unexpected error

java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.class_761.method_22979(class_761.java:1472)
	at net.minecraft.class_761.method_22710(class_761.java:1235)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_761.method_22979(class_761.java:1472)
	at net.minecraft.class_761.method_22710(class_761.java:1235)
	at net.minecraft.class_757.method_3188(class_757.java:1026)

-- Affected level --
Details:
	All players: 1 total; [class_746['SirResigmenduken'/189, l='ClientLevel', x=-65.50, y=63.00, z=184.50]]
	Chunk stats: 1681, 1225
	Level dimension: minecraft:overworld
	Level spawn location: World: (-76,63,176), Section: (at 4,15,0 in -5,3,11; chunk contains blocks -80,0,176 to -65,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 345 game time, 345 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 798260056 bytes (761 MiB) / 1744830464 bytes (1664 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b81
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5671
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29629.16
	Virtual memory used (MB): 20217.91
	Swap memory total (MB): 13312.00
	Swap memory used (MB): 466.85
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amecsapi: Amecs API 1.1.5+mc21w16a
		antiqueatlas: Antique Atlas 6.0.0-fabric-mc1.17.1
		apoli: Apoli 1.0.4
		aqupdgrizzly: Grizzly Bear mob 1.1.1
		architectury: Architectury 2.3.24
		backslot: BackSlot 1.2.0
		backslotaddon: BackSlot Addon 1.0.5
		bedspreads: Bedspreads 1.4.0-1.17
		calio: Calio 1.0.2
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		charmonium: Charmonium 3.3.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.17
		earthtojavamobs: Earth2Java 1.7.1+1.17
		enchant_giver: Enchant Giver 1.1.0
		fabric: Fabric API 0.37.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+2e8bd82f18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.7.0+2e8bd82f18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingleaves: Falling Leaves 1.7.3+1.17.1
		fiber: fiber 0.23.0-2
		healthoverlay: Health Overlay 4.0.1
		inmis: Inmis 2.3.1-1.17
		java: OpenJDK 64-Bit Server VM 16
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kirin: Kirin UI 1.9.1
		maybe-data: Maybe data 1.0.1-1.17
		mcdw: MC Dungeons Weapons 3.3.5
		medievalweapons: Medieval Weapons 1.1.6
		minecraft: Minecraft 1.17.1
		moborigins: Mob Origins 1.6.0
		omega-config: OmegaConfig 1.0.4
		origins: Origins 1.0.3
		origins-classes: Origins: Classes 1.2.2
		pehkui: Pehkui 2.3.0+1.14.4-1.17.1
		pettable: Pettable 1.2.0
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		presencefootsteps: Presence Footsteps r32-1.17-rc1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		roughlyenoughitems: Roughly Enough Items 6.0.267-alpha
		seasons: Fabric Seasons 1.2.2-BETA+1.17
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		torohealth: ToroHealth Damage Indicators 1.17.1-fabric-11
		wolveswitharmor: Wolves With Armor 1.6.0-1.17
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070/PCIe/SSE2 GL version 3.2.0 NVIDIA 456.71, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Player Count: 1 / 8; [class_3222['SirResigmenduken'/189, l='ServerLevel[New World]', x=-65.50, y=63.00, z=184.50]]
	Data Packs: vanilla, Fabric Mods

**Comment by SirResigmenduken** [comment]
After some more testing, it doesn't crash when using reach weapons from MC Dungeon Weapons, so it's probably a confliction with just Medieval Weapons

**Comment by SirResigmenduken** [comment]
It was fixed by the medieval weapons mod team, so this is no longer an issue :)
