### ISSUE TITLE
[Bug]: Game crashes when dying

### ISSUE THREAD

**Issue by Inonedn** [Virtuoel/Pehkui#209]
### Minecraft version(s)

1.17.1

### Mod loader

Forge

### Mod loader version

Forge 37.

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Upon killing myself with the /kill command, the game crashes

### Full list of installed mods

N/A

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>
[crash-2021-11-07_20.10.19-server.txt]
---- Minecraft Crash Report ----
// There are four lights!

Time: 11/7/21, 8:10 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'virtuoel.pehkui.api.ScaleData virtuoel.pehkui.api.ScaleType.getScaleData(net.minecraft.server.level.ServerPlayer)'
	at com.tom.cpm.common.PehkuiInterface.setScale(PehkuiInterface.java:11) ~[CustomPlayerModels-1.17-0.1.1b.jar%2364!:0.1.1b] {re:classloading}
	at com.tom.cpm.common.ServerHandler.lambda$static$6(ServerHandler.java:65) ~[CustomPlayerModels-1.17-0.1.1b.jar%2364!:0.1.1b] {re:classloading,re:mixin}
	at com.tom.cpm.shared.network.NetHandler.onRespawn(NetHandler.java:229) ~[CustomPlayerModels-1.17-0.1.1b.jar%2364!:0.1.1b] {re:classloading,re:mixin}
	at com.tom.cpm.common.ServerHandler.onRespawn(ServerHandler.java:106) ~[CustomPlayerModels-1.17-0.1.1b.jar%2364!:0.1.1b] {re:classloading,re:mixin}
	at net.minecraftforge.eventbus.ASMEventHandler_86_ServerHandler_onRespawn_PlayerRespawnEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.fmllegacy.hooks.BasicEventHooks.firePlayerRespawnEvent(BasicEventHooks.java:54) ~[forge-1.17.1-37.0.104-universal.jar%2382!:?] {re:classloading}
	at net.minecraft.server.players.PlayerList.m_11236_(PlayerList.java:461) ~[client-1.17.1-20210706.113038-srg.jar%2378!:?] {re:mixin,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,re:classloading,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6272_(ServerGamePacketListenerImpl.java:1254) ~[client-1.17.1-20210706.113038-srg.jar%2378!:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(SourceFile:24) ~[client-1.17.1-20210706.113038-srg.jar%2378!:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.m_5797_(SourceFile:6) ~[client-1.17.1-20210706.113038-srg.jar%2378!:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(SourceFile:21) ~[client-1.17.1-20210706.113038-srg.jar%2378!:?] {re:classloading}
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[client-1.17.1-20210706.113038-srg.jar%2378!:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(SourceFile:151) ~[client-1.17.1-20210706.113038-srg.jar%2378!:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(SourceFile:23) ~[client-1.17.1-20210706.113038-srg.jar%2378!:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:775) ~[client-1.17.1-20210706.113038-srg.jar%2378!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:162) ~[client-1.17.1-20210706.113038-srg.jar%2378!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(SourceFile:125) ~[client-1.17.1-20210706.113038-srg.jar%2378!:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:758) ~[client-1.17.1-20210706.113038-srg.jar%2378!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:752) ~[client-1.17.1-20210706.113038-srg.jar%2378!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(SourceFile:134) ~[client-1.17.1-20210706.113038-srg.jar%2378!:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:738) ~[client-1.17.1-20210706.113038-srg.jar%2378!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:687) ~[client-1.17.1-20210706.113038-srg.jar%2378!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.17.1-20210706.113038-srg.jar%2378!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:831) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 735543520 bytes (701 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2060 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f06
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7168
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18741.59
	Virtual memory used (MB): 12944.31
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 54.05
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Player Count: 1 / 8; [ServerPlayer['Inonedn'/1, l='ServerLevel[Blank]', x=0.50, y=70.00, z=0.50]]
	Data Packs: vanilla, mod:cpm (incompatible), mod:worldedit (incompatible), mod:rapid_leaf_decay (incompatible), mod:jei, mod:wthit (incompatible), mod:forge, mod:appleskin (incompatible), mod:torohealth (incompatible), mod:golems (incompatible), mod:curios, mod:xaerominimap (incompatible), mod:xaeroworldmap (incompatible), mod:citadel (incompatible), mod:alexsmobs (incompatible), file/CavesAndCliffsPreview.zip, mod:cavebiomeapi, mod:jeed (incompatible), mod:selene (incompatible), mod:twilightforest, mod:infernalexp (incompatible), mod:calio, mod:caelus, mod:apoli, mod:architectury (incompatible), mod:cloth_config (incompatible), mod:blueprint (incompatible), mod:pehkui (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		infernal-expansion-1.17.1-2.3.2-beta.1.jar        |Infernal Expansion            |infernalexp                   |2.3.2-beta.1        |DONE      |Manifest: NOSIGNATURE
		RapidLeafDecay-1.17.1-2.0.0.jar                   |Rapid Leaf Decay              |rapid_leaf_decay              |2.0.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.17.1-8.1.0.26.jar                           |Just Enough Items             |jei                           |8.1.0.26            |DONE      |Manifest: NOSIGNATURE
		Pehkui-2.5.3+1.17.1-forge.jar                     |Pehkui                        |pehkui                        |2.5.3+1.17.1-forge  |DONE      |Manifest: NOSIGNATURE
		calio-1.17.1-1.0.2.jar                            |Calio                         |calio                         |1.0.2               |DONE      |Manifest: NOSIGNATURE
		wthit-forge-3.10.0.jar                            |wthit                         |wthit                         |3.10.0              |DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.17.1-3.0.0.1.jar                   |Caelus API                    |caelus                        |1.17.1-3.0.0.1      |DONE      |Manifest: NOSIGNATURE
		torohealth-1.17.1-forge-1.jar                     |ToroHealth                    |torohealth                    |1.17.1-forge-1      |DONE      |Manifest: NOSIGNATURE
		extragolems-17.1.1.jar                            |Extra Golems                  |golems                        |17.1.1              |DONE      |Manifest: NOSIGNATURE
		apoli-1.17.1-1.0.4.2.jar                          |Apoli                         |apoli                         |1.0.4.2             |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.17.1-5.0.1.0.jar                   |Curios API                    |curios                        |1.17.1-5.0.1.0      |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.19.0_Forge_1.17.1.jar           |Xaero's Minimap               |xaerominimap                  |21.19.0             |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.17.3_Forge_1.17.1.jar            |Xaero's World Map             |xaeroworldmap                 |1.17.3              |DONE      |Manifest: NOSIGNATURE
		citadel-1.9.3-1.17.1.jar                          |Citadel                       |citadel                       |1.9.3               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.13.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.13.1              |DONE      |Manifest: NOSIGNATURE
		CustomPlayerModels-1.17-0.1.1b.jar                |Customizable Player Models    |cpm                           |0.1.1b              |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.6.jar                           |WorldEdit                     |worldedit                     |7.2.6+4b2d1e7       |DONE      |Manifest: NOSIGNATURE
		cavebiomeapi-1.17.1-1.4.0.jar                     |CaveBiomeAPI                  |cavebiomeapi                  |1.17.1-1.4.0        |DONE      |Manifest: NOSIGNATURE
		jeed-1.17.1-1.2.0.jar                             |Just Enough Effect Description|jeed                          |1.17-1.4.1          |DONE      |Manifest: NOSIGNATURE
		architectury-2.6.35.jar                           |Architectury                  |architectury                  |2.6.35              |DONE      |Manifest: NOSIGNATURE
		blueprint-1.17.1-4.0.1.jar                        |Blueprint                     |blueprint                     |4.0.1               |DONE      |Manifest: NOSIGNATURE
		cloth-config-5.0.38-forge.jar                     |Cloth Config v4 API           |cloth_config                  |5.0.38              |DONE      |Manifest: NOSIGNATURE
		forge-1.17.1-37.0.104-universal.jar               |Forge                         |forge                         |37.0.104            |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		appleskin-forge-mc1.17.1-2.1.0.jar                |AppleSkin                     |appleskin                     |2.1.0               |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.17.1-4.0.812-universal.jar       |The Twilight Forest           |twilightforest                |4.0.812             |DONE      |Manifest: NOSIGNATURE
		selene-1.17.1-1.9.0.jar                           |Selene                        |selene                        |1.17.1-1.1          |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: b3d808d4-d7c9-40c1-8c0b-03678b745b3c
	FML: 37.0
	Forge: net.minecraftforge:37.0.104

**Comment by Virtuoel** [comment]
After some investigating, looks like an issue with CustomPlayerModels. One of the method stubs they made for calling Pehkui's API seems to be using the wrong argument type. Report to them if this crash still occurs with the latest versions of both mods.
