### ISSUE TITLE
I can't place lecterns

### ISSUE THREAD

**Issue by TheJetNinja** [Virtuoel/Pehkui#258]
so on my 1.18.1 server with origins, extra origins, mob origins, gate of babylon and pehkui,  whenever i try to place a lectern my game crashes. here is what it says in console when my game crashes.

[07:46:41] [Server thread/WARN]: @ModifyConstant conflict. Skipping mixins.reach-entity-attributes.json:InventoryValidationMixin->@ModifyConstant::getActualReachDistance(DLnet/minecraft/class_1657;)D from mod reach-entity-attributes with priority 1000, already redirected by pehkui.mixins.json:LecternBlockEntityMixin->@ModifyConstant::canPlayerUseModifyDistance(DLnet/minecraft/class_1657;)D from mod pehkui with priority 1000
[07:46:41] [Server thread/FATAL]: Error executing task on Server
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3722$1 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_3722.<init>(class_3722.java:40) ~[server-intermediary.jar:?]
	at net.minecraft.class_3715.method_10123(class_3715.java:153) ~[server-intermediary.jar:?]
	at net.minecraft.class_2818.method_12010(class_2818.java:265) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_30092(class_1937.java:213) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_8652(class_1937.java:198) ~[server-intermediary.jar:?]
	at net.minecraft.class_1747.method_7708(class_1747.java:159) ~[server-intermediary.jar:?]
	at net.minecraft.class_1747.method_7712(class_1747.java:76) ~[server-intermediary.jar:?]
	at net.minecraft.class_1747.method_7884(class_1747.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.class_1799.method_7981(class_1799.java:240) ~[server-intermediary.jar:?]
	at net.minecraft.class_3225.method_14262(class_3225.java:347) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12046(class_3244.java:1057) ~[server-intermediary.jar:?]
	at net.minecraft.class_2885.method_12547(class_2885.java:30) ~[server-intermediary.jar:?]
	at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	... 30 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method getActualReachDistance(DLnet/minecraft/class_1657;)D in mixins.reach-entity-attributes.json:InventoryValidationMixin from mod reach-entity-attributes failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap refmap.reach-entity-attributes.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	... 30 more

**Comment by MiracleKnows** [comment]
+1 I'm also having the same issue with lecturns on my 1.18.1 server. I remembered that I had an outdated version in another modpack and used it (Pehkui-3.1.0+1.14.4-1.18.1), and it doesn't appear to have the same issue. The problem might've been something added to the future versions, if that can help!

**Comment by TheJetNinja** [comment]
> +1 I'm also having the same issue with lecturns on my 1.18.1 server. I remembered that I had an outdated version in another modpack and used it (Pehkui-3.1.0+1.14.4-1.18.1), and it doesn't appear to have the same issue. The problem might've been something added to the future versions, if that can help!

thank you so much

**Comment by ChloeDawn** [comment]
This is an incompatibility with Reach Entity Attributes, Pehkui is redirecting the same constant value in `LecternBlockEntity$1`. Related: https://github.com/JamiesWhiteShirt/reach-entity-attributes/issues/15

**Comment by TranquilStar** [comment]
I was able to fix this issue by downgrading pehkui so it has something to do with the newer version for 1.18.1 not sure about 1.18.2

**Comment by TranquilStar** [comment]
Pehkui-3.1.0+1.14.4-1.18.1.jar this was the version that I downgraded too but for 1.18.1 not sure for 1.18.2

**Comment by Alec153** [comment]
I hope this gets a fix for 1.18.2 soon. It's the only bug holding my modpack back. I would try to play around it but thats impossible due to world gen.

**Comment by TheRanker** [comment]
Pehkui-3.2.0+1.14.4-1.19.jar is the version trhat currently has the issues for 1.18.2... Alec if you want to procede with your modpack.. remove pehkui and bewitchment mods.  and youll be fine... ive removed pehkui and never seen the crash again.. only bewitchment depends on it for me.. so its a safew removal for time being until this gets fixed on pehkui side. horrible crash.

**Comment by Alec153** [comment]
> Pehkui-3.2.0+1.14.4-1.19.jar is the version trhat currently has the issues for 1.18.2... Alec if you want to procede with your modpack.. remove pehkui and bewitchment mods. and youll be fine... ive removed pehkui and never seen the crash again.. only bewitchment depends on it for me.. so its a safew removal for time being until this gets fixed on pehkui side. horrible crash.

Appreciated however bewitchment is the most important mod to my friends playing the modpack.
