### ISSUE TITLE
[Bug]: Cannot load on 1.18.2

### ISSUE THREAD

**Issue by Arathain** [Virtuoel/Pehkui#261]
### Minecraft version(s)

1.18.2

### Mod loader

Fabric

### Mod loader version

Fabric Loader 0.13.3

### Fabric API version

Fabric API 0.48.0

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Game forces itself to run safe mode or not run: expected for world to load normally
all ran in a dev environment, however the mod in question itself doesn't touch any of the code failing here
Didn't crash, but the log is probably relevant:

([19:06:29] [Render thread/ERROR] (FabricLoader/Mixin) Mixin apply for mod pehkui failed pehkui.mixins.json:compat118minus.ServerPlayerInteractionManagerMixin -> net.minecraft.server.network.ServerPlayerInteractionManager: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyConstant annotation on processBlockBreakingActionModifyDistance could not find any targets matching '@Desc(owner = ServerPlayerInteractionManager.class, value = "method_14263", args = { BlockPos.class, PlayerActionC2SPacket$Action.class, Direction.class, int.class })' in net.minecraft.server.network.ServerPlayerInteractionManager. Using refmap Pehkui-refmap.json [PREINJECT Applicator Phase -> pehkui.mixins.json:compat118minus.ServerPlayerInteractionManagerMixin -> Prepare Injections ->  -> constant$zjk000$processBlockBreakingActionModifyDistance(D)D -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyConstant annotation on processBlockBreakingActionModifyDistance could not find any targets matching '@Desc(owner = ServerPlayerInteractionManager.class, value = "method_14263", args = { BlockPos.class, PlayerActionC2SPacket$Action.class, Direction.class, int.class })' in net.minecraft.server.network.ServerPlayerInteractionManager. Using refmap Pehkui-refmap.json [PREINJECT Applicator Phase -> pehkui.mixins.json:compat118minus.ServerPlayerInteractionManagerMixin -> Prepare Injections ->  -> constant$zjk000$processBlockBreakingActionModifyDistance(D)D -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.ModifyConstantInjectionInfo.<init>(ModifyConstantInjectionInfo.java:54) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at jdk.internal.reflect.GeneratedConstructorAccessor22.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.server.SaveLoader.ofLoaded(SaveLoader.java:33) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.createSaveLoader(MinecraftClient.java:1892) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient.java:1765) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.createWorld(MinecraftClient.java:1740) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.createLevel(CreateWorldScreen.java:245) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.method_19922(CreateWorldScreen.java:195) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget.java:34) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget.java:28) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget.java:127) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:39) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.Mouse.method_1611(Mouse.java:90) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:496) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:90) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.Mouse.method_22686(Mouse.java:167) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:101) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.Mouse.method_22684(Mouse.java:167) ~[minecraft-project-@-merged-named.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:174) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1079) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:724) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:213) [minecraft-project-@-merged-named.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
[19:06:29] [Render thread/WARN] (Minecraft) Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Mixin transformation of net.minecraft.server.network.ServerPlayerInteractionManager failed
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.client.MinecraftClient.createSaveLoader(MinecraftClient.java:1894) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient.java:1765) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.createWorld(MinecraftClient.java:1740) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.createLevel(CreateWorldScreen.java:245) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.method_19922(CreateWorldScreen.java:195) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget.java:34) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget.java:28) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget.java:127) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:39) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.Mouse.method_1611(Mouse.java:90) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:496) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:90) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.Mouse.method_22686(Mouse.java:167) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:101) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.Mouse.method_22684(Mouse.java:167) ~[minecraft-project-@-merged-named.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:174) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1079) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:724) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:213) [minecraft-project-@-merged-named.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.server.network.ServerPlayerInteractionManager failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.server.SaveLoader.ofLoaded(SaveLoader.java:33) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.createSaveLoader(MinecraftClient.java:1892) ~[minecraft-project-@-merged-named.jar:?]
	... 29 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.server.SaveLoader.ofLoaded(SaveLoader.java:33) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.createSaveLoader(MinecraftClient.java:1892) ~[minecraft-project-@-merged-named.jar:?]
	... 29 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [pehkui.mixins.json:compat118minus.ServerPlayerInteractionManagerMixin] from phase [DEFAULT] in config [pehkui.mixins.json] from mod [pehkui] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.server.SaveLoader.ofLoaded(SaveLoader.java:33) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.createSaveLoader(MinecraftClient.java:1892) ~[minecraft-project-@-merged-named.jar:?]
	... 29 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyConstant annotation on processBlockBreakingActionModifyDistance could not find any targets matching '@Desc(owner = ServerPlayerInteractionManager.class, value = "method_14263", args = { BlockPos.class, PlayerActionC2SPacket$Action.class, Direction.class, int.class })' in net.minecraft.server.network.ServerPlayerInteractionManager. Using refmap Pehkui-refmap.json [PREINJECT Applicator Phase -> pehkui.mixins.json:compat118minus.ServerPlayerInteractionManagerMixin -> Prepare Injections ->  -> constant$zjk000$processBlockBreakingActionModifyDistance(D)D -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.ModifyConstantInjectionInfo.<init>(ModifyConstantInjectionInfo.java:54) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at jdk.internal.reflect.GeneratedConstructorAccessor22.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.server.SaveLoader.ofLoaded(SaveLoader.java:33) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.createSaveLoader(MinecraftClient.java:1892) ~[minecraft-project-@-merged-named.jar:?]
	... 29 more
)

### Full list of installed mods

[19:05:46] [main/INFO] (FabricLoader) Loading 64 mods:
	- cardinal-components-base 4.1.4
	- cardinal-components-entity 4.1.4
	- cloth-basic-math 0.6.0
	- cloth-config 6.2.57
	- cloth-config-lite 2.0.6
	- connectiblechains 2.1.1+1.18.2
	- fabric 0.48.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860
	- fabric-api-lookup-api-v1 1.5.7+d7c144a860
	- fabric-biome-api-v1 8.0.3+801ec85b60
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560
	- fabric-command-api-v1 1.1.9+d7c144a860
	- fabric-commands-v0 0.2.8+b4f4f6cd60
	- fabric-containers-v0 0.1.21+d7c144a860
	- fabric-content-registries-v0 3.0.2+d82b939260
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560
	- fabric-data-generation-api-v1 2.0.7+6d3e563660
	- fabric-dimensions-v1 2.1.17+2540745460
	- fabric-entity-events-v1 1.4.8+d7c144a860
	- fabric-events-interaction-v0 0.4.19+d7c144a860
	- fabric-events-lifecycle-v0 0.2.13+d7c144a860
	- fabric-game-rule-api-v1 1.0.13+d7c144a860
	- fabric-gametest-api-v1 1.0.15+2540745460
	- fabric-item-api-v1 1.3.3+691a79b560
	- fabric-item-groups-v0 0.3.10+3ac43d9560
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60
	- fabric-lifecycle-events-v1 2.0.2+2540745460
	- fabric-loot-tables-v1 1.0.11+d7c144a860
	- fabric-mining-level-api-v1 2.0.4+d1027f7d60
	- fabric-models-v0 0.3.6+d7c144a860
	- fabric-networking-api-v1 1.0.21+d882b91560
	- fabric-networking-v0 0.3.8+b4f4f6cd60
	- fabric-object-builder-api-v1 2.0.3+40c91ec860
	- fabric-particles-v1 0.2.12+526dc1ac60
	- fabric-registry-sync-v0 0.9.8+0d9ab37260
	- fabric-renderer-api-v1 0.4.13+d882b91560
	- fabric-renderer-indigo 0.4.17+d8c7b9ae60
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60
	- fabric-rendering-v0 1.1.13+b4f4f6cd60
	- fabric-rendering-v1 1.10.7+54e5b2ec60
	- fabric-resource-conditions-api-v1 2.0.2+d1027f7d60
	- fabric-resource-loader-v0 0.4.18+2de5574560
	- fabric-screen-api-v1 1.0.10+d882b91560
	- fabric-screen-handler-api-v1 1.1.14+40c91ec860
	- fabric-textures-v0 1.0.12+3ac43d9560
	- fabric-transfer-api-v1 1.5.14+cca23f9360
	- fabric-transitive-access-wideners-v1 1.0.0+40c91ec860
	- fabricloader 0.13.3
	- fabricshieldlib 1.5.3-1.18
	- geckolib3 3.0.32
	- java 17
	- kanos_config 0.1.5+1.14.4-1.18.2
	- minecraft 1.18.2
	- mm 2.3
	- modmenu 3.1.0
	- omega-config 1.2.3-1.18.1
	- omega-config-gui 1.2.3-1.18.1
	- pehkui 3.2.1+1.14.4-1.19
	- reach-entity-attributes 2.1.1
	- satin 1.7.2
	- tot 1.0.0

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
Should now be resolved in Pehkui 3.2.2.
