### ISSUE TITLE
[Bug]: Untitled bug report

### ISSUE THREAD

**Issue by TwiningShiningDawn** [Virtuoel/Pehkui#280]
### Minecraft version(s)

1.18.2

### Mod loader

Fabric

### Mod loader version

Fabric 0.10.2

### Fabric API version

fabric-api-0.51.1+1.18.2

### In what environment did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

whenever i attempt to launch the game, it goes to the fabric crash report, when i remove the mod from the folder, and also the ones depending on it, the game launches fine, but i would like to use the mods, so i need this one.

### Full list of installed mods

amecs-1.3.7+mc1.18.2.jar
antighost-1.18.2-fabric0.47.10-1.1.4.jar
Apoli-1.18.2-2.3.3.jar
appleskin-fabric-mc1.18.2-2.4.0.jar
architectury-4.2.50.jar
architectury-4.3.53.jar
architectury-4.4.56.jar
auudio_fabric_1.0.3_MC_1.18-1.18.2.jar
AwesomeDungeonEnd-Fabric-1.18.2-1.0.1.jar
AwesomeDungeonFabric-1.18.1-2.0.8.jar
AwesomeDungeonNether-Fabric-1.18.2-1.0.1.jar
badpackets-fabric-0.1.2.jar
bclib-1.4.5.jar
betterbeds-1.2.0.jar
better-end-1.1.0.jar
BetterF3-1.2.4-fabric-1.18.2
blossom-1.18.2-1.0.4.jar
blur-2.4.1.jar
chipped-1.2.jar
clothconfig-6.2.57-fabric.jar
consistency_plus-0.5.0+1.18.2-fabric.jar
continuity-1.1.0+1.18.2.jar
creeperoverhaul-1.18.2-1.3.1-fabric.jar
cullleaves-2.3.2.jar
dashloader-def-3.1.1+1.18.jar
dynamic-fps-2.1.0.jar
easiercrafting-1.18.2-fabric0.47.10-1.7.jar
endemic-1.18.2-1.2.1.jar
enhancedblockentities-0.6+1.18.2.jar
EnvironmentalArmor-1.18.2-1.4.4.jar
Essential-fabric_1-18-2.jar
expandability-6.0.0.jar
fabric-api-0.51.1+1.18.2.jar
fabric-language-kotlin-1.7.4+kotlin.1.6.21.jar
factions-mc1.18.2-1.5.0 (1).jar
fallingleaves-1.10.0+1.18.2.jar
fancymenu_fabric_2.7.0_MC_1.18.2.jar
feature_nbt_deadlock_be_gone_fabric-2.0.0+1.18.2-rc1.jar
ferritecore-4.2.1-fabric,jar
fm_audio_extension_fabric_1.0.0_MC_1.18-1.18.2.jar
ForgeConfigAPIPort-v3.2.0-1.18.2-Fabric.jar
geckolib-fabric-1.18-3.0.42.jar
here-be-no-dragons-1.0.0.jar
Iceberg-1.18.2-fabric-1.0.38.jar
Iceberg-1.18.2-fabric-1.0.38.jar
InventoryHUD-fabric-[1.18]+-3.4.2.jar
konkrete_fabric_1.3.3-1_MC_1.18-1.18.2.jar
krypton-0.1.9.jar
lazydfu-0.1.2.jar
LegendaryTooltips-1.18.2-fabric-1.2.4.jar
LibraryFerret-Fabric-1.18.2-1.0.3.jar
lithium-fabric-mc1.18.2-0.7.9.jar
loadmyresources_fabric_1.0.1-1_MC_1.18.jar
magehand-1.1.2.jar
malilib-fabric-1.18.2-0.12.1.jar
minihud-fabric-1.18.2-0.22.0.jar
mobscarecrow-1.2.2.jar
modmenu-3.2.1.jar
mostructures-1.4.1+1.18.2.jar
mousewheelie-1.8.8+mc1.18.2.jar
mythicmetals-0.13.1.jar
nears-fabric-1.18-1.1.8.jar
nears-fabric-1.18-1.1.8.jar
notenoughcrashes-4.1.6+1.18.2-fabric.jar
OfflineSkins-1.18.2-v1-fabric.jar
okzoomer-5.0.0-beta.6+1.18.2.jar
Origins-1.18.2-1.4.1.jar
owo-lib-0.7.1+1.18.jar
paradise-lost-1.6.8+1.18.2.jar
Pehkui-3.3.1+1.14.4-1.19.jar
phosphor-fabric-mc1.18.x-0.8.1.jar
plasmovoice-fabric-1.18.2-1.2.11-hotfix1.jar
purpurclient-1.18.2-3.jar
raised-fabric-1.18.2-1.0.7.jar
reeses_sodium_options-mc1.18.2-1.4.2.jar
replaymod-1.18.2-2.6.5.jar
repurposed_structures_fabric-4.1.6+1.18.2.jar
RoughlyEnoughItems-8.1.457.jar
signtools-fabric.1.18-1.0.0.jar
skylorlib-1.3.35.jar
sodium-extra-mc1.18.2-0.4.3.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
spark-1.9.1-fabric.jar
statuseffecttimer-1.1.1+1.18.1.jar
stonecutter_recipe_tags-3.0.1+1.18.bc850d5.fabric.jar
stoneholm-1.4.3.jar
Subterrestrial-1.0.2.jar
Terralith_v2.2.1a.jar
TheExtractinator-1.0.8.jar
tl_skin_cape_fabric_1.18.2-1.26.jar
tl_skin_cape_forge_1.18_1.18.2-1.25.jar
torohealth-1.18-fabric-2.jar
trinkets-3.3.0.jar
twigs-fabric-1.1.3-patch1+1.18.2.jar
variantbarrels-1.4.0.jar
wraith-alloy-forgery-2.0.13+1.18.jar
wthit-fabric-4.8.2.jar
wthit-fabric-4.9.1.jar
YungsApi-1.18.2-Fabric-2.0.8.jar
YungsBetterDungeons-1.18.2-Fabric-2.1.0.jar
YungsBetterMineshafts-1.18.2-Fabric-2.1.0.jar
YungsBetterStrongholds-1.18.2-Fabric-2.1.1.jar
YungsBridges-1.18.2-Fabric-2.1.0.jar
YungsExtras-1.18.2-Fabric-2.1.0.jar

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>
```
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1501 failed
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1501 failed
	at net.minecraft.entity.EntityType.<clinit>(EntityType:210)
	at net.minecraft.world.gen.feature.DungeonFeature.<clinit>(DungeonFeature:28)
	at net.minecraft.world.gen.feature.Feature.<clinit>(Feature:83)
	at net.minecraft.world.gen.feature.OceanConfiguredFeatures.<clinit>(OceanConfiguredFeatures:20)
	at net.minecraft.world.gen.feature.ConfiguredFeatures.getDefaultConfiguredFeature(ConfiguredFeatures:23)
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:86)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:85)
	at net.minecraft.util.registry.Registry.<clinit>(Registry:291)
	at net.minecraft.Bootstrap.initialize(Bootstrap:49)
	at net.minecraft.client.main.Main.main(Main:153)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1501 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 18 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 21 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [pehkui.mixins.json:LlamaEntityMixin] from phase [DEFAULT] in config [pehkui.mixins.json] from mod [pehkui] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 24 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("CONSTANT") on net/minecraft/class_1501::updatePassengerPositionModifyOffset with priority 1000 cannot inject into net/minecraft/class_1501::method_5865(Lnet/minecraft/class_1297;)V merged by org.purpurmc.purpur.client.mixin.mob.MixinLlama with priority 1000 [PREINJECT Applicator Phase -> pehkui.mixins.json:LlamaEntityMixin -> Prepare Injections ->  -> constant$daj000$updatePassengerPositionModifyOffset(F)F -> Prepare]
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 24 more

```

**Comment by Virtuoel** [comment]
Looks like Purpur Client's overwriting some passenger methods in a not as compatible manner. Seems this has already been reported over at https://github.com/PurpurMC/PurpurClient/issues/17, so I'll be closing this in favor of their issue.
