### ISSUE TITLE
Pehkui causes agricraft seed analyzer to crash client

### ISSUE THREAD

**Issue by Mazereck** [Virtuoel/Pehkui#291]
### Minecraft version(s)

1.18.2

### Mod loader

Forge

### Mod loader version

Forge 40.1.48

### In what environment did the problem occur?

Both singleplayer and multiplayer

### What went wrong? (Crash logs don't go here)

Attempting to use the AgriCraft seed analyzer results in the game crashing.
Reported to AgriCraft dev but they directed me to report it here instead.

### Full list of installed mods

AgriCraft: 3.1.3
InfinityLib: 2.1.3
Pehkui: 3.3.2
Origins Forge: 1.4.1.3
Bucolic Origins Forge: 3.2
Caelus Forge 3.0.0.2

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 6/20/22, 3:49 AM
Description: Unexpected error

java.lang.NullPointerException: Cannot enter synchronized block because "this.pehkui_scaleTypes" is null
	at net.minecraft.world.entity.Entity.pehkui_getScaleData(Entity.java:4775) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:additionalentityattributes:apoli_prevent_suffocation,re:classloading,pl:accesstransformer:B,xf:fml:additionalentityattributes:apoli_prevent_suffocation,pl:mixin:APP:origins.mixins.json:SelectionInvulnerabilityMixin,pl:mixin:APP:apoli.mixins.json:EntityAccessor,pl:mixin:APP:apoli.mixins.json:EntityMixin,pl:mixin:APP:pehkui.mixins.json:EntityMixin,pl:mixin:APP:pehkui.mixins.json:compat116plus.EntityMixin,pl:mixin:APP:pehkui.mixins.json:compat117plus.EntityMixin,pl:mixin:APP:pehkui.mixins.json:step_height.EntityMixin,pl:mixin:APP:pehkui.mixins.json:compat117plus.patchwork.compat.EntityCalculateDimensionsMixin,pl:mixin:A}
	at virtuoel.pehkui.api.ScaleType.getScaleData(ScaleType.java:34) ~[Pehkui-3.3.2+1.18.2-forge.jar%2357!/:?] {re:mixin,re:classloading}
	at virtuoel.pehkui.util.ScaleUtils.getTypedScale(ScaleUtils.java:595) ~[Pehkui-3.3.2+1.18.2-forge.jar%2357!/:?] {re:mixin,re:classloading}
	at virtuoel.pehkui.util.ScaleUtils.getBoundingBoxWidthScale(ScaleUtils.java:385) ~[Pehkui-3.3.2+1.18.2-forge.jar%2357!/:?] {re:mixin,re:classloading}
	at virtuoel.pehkui.util.ScaleUtils.modifyProjectionMatrixDepth(ScaleUtils.java:154) ~[Pehkui-3.3.2+1.18.2-forge.jar%2357!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.GameRenderer.constant$zij000$getBasicProjectionMatrixModifyDepth(GameRenderer.java:2517) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat117plus.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_172716_(GameRenderer.java:807) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat117plus.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1027) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat117plus.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:835) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat117plus.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.48.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.world.entity.Entity.pehkui_getScaleData(Entity.java:4775) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:additionalentityattributes:apoli_prevent_suffocation,re:classloading,pl:accesstransformer:B,xf:fml:additionalentityattributes:apoli_prevent_suffocation,pl:mixin:APP:origins.mixins.json:SelectionInvulnerabilityMixin,pl:mixin:APP:apoli.mixins.json:EntityAccessor,pl:mixin:APP:apoli.mixins.json:EntityMixin,pl:mixin:APP:pehkui.mixins.json:EntityMixin,pl:mixin:APP:pehkui.mixins.json:compat116plus.EntityMixin,pl:mixin:APP:pehkui.mixins.json:compat117plus.EntityMixin,pl:mixin:APP:pehkui.mixins.json:step_height.EntityMixin,pl:mixin:APP:pehkui.mixins.json:compat117plus.patchwork.compat.EntityCalculateDimensionsMixin,pl:mixin:A}
	at virtuoel.pehkui.api.ScaleType.getScaleData(ScaleType.java:34) ~[Pehkui-3.3.2+1.18.2-forge.jar%2357!/:?] {re:mixin,re:classloading}
	at virtuoel.pehkui.util.ScaleUtils.getTypedScale(ScaleUtils.java:595) ~[Pehkui-3.3.2+1.18.2-forge.jar%2357!/:?] {re:mixin,re:classloading}
	at virtuoel.pehkui.util.ScaleUtils.getBoundingBoxWidthScale(ScaleUtils.java:385) ~[Pehkui-3.3.2+1.18.2-forge.jar%2357!/:?] {re:mixin,re:classloading}
	at virtuoel.pehkui.util.ScaleUtils.modifyProjectionMatrixDepth(ScaleUtils.java:154) ~[Pehkui-3.3.2+1.18.2-forge.jar%2357!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.GameRenderer.constant$zij000$getBasicProjectionMatrixModifyDepth(GameRenderer.java:2517) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat117plus.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_172716_(GameRenderer.java:807) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat117plus.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1027) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat117plus.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Mazereck'/587, l='ClientLevel', x=27.82, y=78.00, z=118.12]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (32,76,112), Section: (at 0,12,0 in 2,4,7; chunk contains blocks 32,-64,112 to 47,319,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 252 game time, 252 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2260) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.48.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3103915408 bytes (2960 MiB) / 4362076160 bytes (4160 MiB) up to 9663676416 bytes (9216 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3800XT 8-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.90
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2080 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e81
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1295
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Virtual memory max (MB): 51232.83
	Virtual memory used (MB): 33579.61
	Swap memory total (MB): 26734.96
	Swap memory used (MB): 3386.60
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9216m -Xms256m
	Launched Version: forge-40.1.48
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.95, NVIDIA Corporation
	Window size: 1024x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3800XT 8-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Mazereck'/587, l='ServerLevel[New World]', x=27.82, y=78.00, z=118.12]]
	Data Packs: vanilla, mod:pehkui (incompatible), mod:caelus (incompatible), mod:forge, mod:additionalentityattributes, mod:infinitylib (incompatible), mod:agricraft (incompatible), mod:bucolicorigins (incompatible)
	World Generation: Stable
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		Pehkui-3.3.2+1.18.2-forge.jar                     |Pehkui                        |pehkui                        |3.3.2+1.18.2-forge  |DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.18.1-3.0.0.2.jar                   |Caelus API                    |caelus                        |1.18.1-3.0.0.2      |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.48-universal.jar                |Forge                         |forge                         |40.1.48             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Origins-1.18.2-1.4.1.3-unified.jar                |Additional Entity Attributes  |additionalentityattributes    |1.18.2-1.4.1.3      |DONE      |Manifest: NOSIGNATURE
		infinitylib-2.1.3.jar                             |InfinityLib                   |infinitylib                   |1.18.2-2.1.3        |DONE      |Manifest: NOSIGNATURE
		agricraft-1.18.2-3.1.3.jar                        |AgriCraft                     |agricraft                     |1.18.2-3.1.3        |DONE      |Manifest: NOSIGNATURE
		bucolicorigins-3.2[FORGE-CHOOSE-COMPATIBLE].jar   |Bucolic_Origins               |bucolicorigins                |1.0                 |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 74132038-cdf2-4fc8-b016-1f0c2dcfa29b
	FML: 40.1
	Forge: net.minecraftforge:40.1.48

**Comment by Virtuoel** [comment]
After[ ](https://github.com/AgriCraft/AgriCraft/issues/1463)some testing, turns out this is caused by [InfinityLib](https://github.com/InfinityRaider/InfinityLib)'s dynamic camera, specifically the way it's [instantiated](https://github.com/InfinityRaider/InfinityLib/blob/3451458b0c6416d99a45abdea8a1c73914195553/src/main/java/com/infinityraider/infinitylib/modules/dynamiccamera/DynamicCamera.java#L35), using `Unsafe` and having to [initialize fields that shouldn't be null](https://github.com/InfinityRaider/InfinityLib/blob/3451458b0c6416d99a45abdea8a1c73914195553/src/main/java/com/infinityraider/infinitylib/utility/UnsafeUtil.java#L211-L212), which unsurprisingly can't take into account [fields added by a mod's mixins](https://github.com/Virtuoel/Pehkui/blob/fedb16ed00d46ffe1153e383eb63c811c82b9975/src/main/java/virtuoel/pehkui/mixin/EntityMixin.java#L42) whose types are not in that list.
