### ISSUE TITLE
Un able to join your world

### ISSUE THREAD

**Issue by wxjk-1** [Virtuoel/Pehkui#298]
### Minecraft version(s)

Other (specify below)

### Minecraft version details

Playing in 1.19

### Mod loader

Fabric

### Mod loader version

Fabric 0.14.8

### Fabric API version

Fabric API 0.57.0

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

If you scale is too big it crashes your game and when you try to join again it won't let you it just crashes again.

### Full list of installed mods

Bits and Chisels
Cloth config api
entity culling
Fabric API
immersive portals
Just enough items
miniscaled
Pehkui
World edit
Gravity api

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

---- Minecraft Crash Report ----
// My bad.

Time: 7/7/22, 9:50 AM
Description: Unexpected error

java.lang.IllegalArgumentException: too big
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158)
	at qouteall.imm_ptl.core.McHelper.foreachEntities(McHelper.java:482)
	at qouteall.imm_ptl.core.McHelper.findEntities(McHelper.java:455)
	at qouteall.imm_ptl.core.McHelper.findEntitiesRough(McHelper.java:516)
	at qouteall.imm_ptl.core.McHelper.getEntitiesNearby(McHelper.java:189)
	at qouteall.imm_ptl.core.commands.PortalCommand.raytracePortals(PortalCommand.java:2066)
	at qouteall.imm_ptl.core.commands.PortalCommand.getPlayerPointingPortalRaw(PortalCommand.java:2060)
	at qouteall.imm_ptl.core.block_manipulation.BlockManipulationClient.updatePointedBlock(BlockManipulationClient.java:67)
	at net.minecraft.class_757.handler$zpk000$onUpdateTargetedEntityFinish(class_757.java:2532)
	at net.minecraft.class_757.method_3190(class_757.java:637)
	at net.minecraft.class_757.method_3188(class_757.java:994)
	at net.minecraft.class_757.redirect$bad000$redirectRenderingWorld(class_757.java:3150)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158)
	at qouteall.imm_ptl.core.McHelper.foreachEntities(McHelper.java:482)
	at qouteall.imm_ptl.core.McHelper.findEntities(McHelper.java:455)
	at qouteall.imm_ptl.core.McHelper.findEntitiesRough(McHelper.java:516)
	at qouteall.imm_ptl.core.McHelper.getEntitiesNearby(McHelper.java:189)
	at qouteall.imm_ptl.core.commands.PortalCommand.raytracePortals(PortalCommand.java:2066)
	at qouteall.imm_ptl.core.commands.PortalCommand.getPlayerPointingPortalRaw(PortalCommand.java:2060)
	at qouteall.imm_ptl.core.block_manipulation.BlockManipulationClient.updatePointedBlock(BlockManipulationClient.java:67)
	at net.minecraft.class_757.handler$zpk000$onUpdateTargetedEntityFinish(class_757.java:2532)
	at net.minecraft.class_757.method_3190(class_757.java:637)
	at net.minecraft.class_757.method_3188(class_757.java:994)
	at net.minecraft.class_757.redirect$bad000$redirectRenderingWorld(class_757.java:3150)

-- Affected level --
Details:
	All players: 1 total; [class_746['Josiahcat333'/216, l='ClientWorld minecraft:overworld', x=-102.44, y=10.00, z=84.73]]
	Chunk stats: Client Chunks (ImmPtl) 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (-64,63,96), Section: (at 0,15,0 in -4,3,6; chunk contains blocks -64,-64,96 to -49,319,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 592684 game time, 428609 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:758)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Mac OS X (aarch64) version 12.0.1
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1015369272 bytes (968 MiB) / 3355443200 bytes (3200 MiB) up to 22833790976 bytes (21776 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1 Pro
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple G13X
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 35840.00
	Virtual memory used (MB): 19219.50
	Swap memory total (MB): 3072.00
	Swap memory used (MB): 1933.75
	JVM Flags: 2 total; -Xmx21768m -Xms556m
	Fabric Mods: 
		bitsandchisels: BitsAndChisels 2.7.0
			stacc: Stacc 1.3.4
		cloth-config: Cloth Config v6 7.0.72
			cloth-basic-math: cloth-basic-math 0.6.1
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		fabric: Fabric API 0.57.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabricloader: Fabric Loader 0.14.8
		gravity_api: Gravity API 0.7.12
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		immersive_portals: Immersive Portals 2.0.4
imm_ptl_core: Immersive Portals Core 2.0.4
			q_misc_util: QMiscUtil 2.0.4
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.0.0.206
minecraft: Minecraft 1.19
		mini_scaled: MiniScaled 2.0.0
		pehkui: Pehkui 3.3.3+1.14.4-1.19.1
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		redstonebits: Redstone Bits 1.8.2
		tooltipfix: ToolTip Fix 1.0.5-1.19
		worldedit: WorldEdit 7.2.11-beta-01+6200-0877589
	Launched Version: fabric-loader-0.14.8-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Apple M1 Pro GL version 4.1 Metal - 76.1, Apple
	Window size: 3024x1890
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x Apple M1 Pro
	Server Running: true
	Player Count: 1 / 8; [class_3222['Josiahcat333'/216, l='ServerWorld minecraft:overworld New World', x=-102.44, y=10.00, z=84.73]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable

**Comment by Virtuoel** [comment]
Looks like the crash comes from somewhere in Immersive Portals. I'd recommend reporting to them instead.

**Comment by wxjk-1** [comment]
it is in immersive portals
