### ISSUE TITLE
1.19 Pose Stack Not Empty Exception

### ISSUE THREAD

**Issue by Bullseye55** [Virtuoel/Pehkui#299]
### Minecraft version(s)

1.19.1

### Minecraft version details

N/A

### Mod loader

Fabric

### Mod loader version

14.8

### Fabric API version

0.57.0

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

A random crash in Creative while flying around. Human origin, no class chosen, nothing special from its end. Upon reloading the world, it would occur again within less than a second.

Removing Pehkui and the hard-requirement mods(Origins++, Medieval Origins, Bewitchment+BewitchmentPlus+Besmirtchment), caused the world to load normally and function optimally.

### Full list of installed mods

- additionaladditions 5.0.1
	- additionalbars 3.3.1+1.19
	- additionalentityattributes 1.0.0+1.19 via apoli
	- additionalstructures 4.0.0
	- advanced_reborn 1.0.8
	- advanced_runtime_resource_pack 0.6.2
	- aiotexpanded 1.0.4-1.19
	- allarrowsinfinityfix 1.3
	- alloy_forgery 2.0.15+1.19
	- alternate-current 1.4.0
	- another_furniture 2.0.1-1.19
	- apocalypse 0.2.23
	- apoli 2.5.1 via origins
	- appleskin 2.4.0+mc1.19
	- apugli 1.8.2+1.19-fabric via toomanyorigins
	- architects_palette 2.1.1
	- architectury 5.9.30
	- artifacts 7.1.1+fabric
	- autoconfig1u 3.4.0 via advanced_reborn
	- awesomeflooring 2.0.1
	- axesareweapons 1.6.0
	- axolotlitemfix 1.1.3
	- badpackets 0.1.2
	- balm-fabric 4.3.0+0
	- basicaiots 1.4+1.19
	- bclib 2.0.15
	- besmirchment 1.19-1
	- betteranimalmodels 1.19-5.6.0
	- betteranimalsplus 1.19-11.0.6
	- betterend 2.0.9
	- betternether 7.0.6
	- bewitchment 1.19-1
	- biom4st3r_libs_biow0rks_reflection 0.1.5 via moenchantments
	- biomemakeover 1.19-1.5.8
	- biow0rks-base 0.2.10 via moenchantments
	- bitsandchisels 2.7.0
	- blockus 2.5.1+1.19
	- blue_endless_jankson 1.2.1 via jankson
	- bookshelf 14.1.7
	- bwplus 1.19-2
	- byg 2.0.0.7
	- calio 1.7.0 via apoli
	- cardinal-components 5.0.1
	- cardinal-components-base 5.0.1 via cardinal-components
	- cardinal-components-block 5.0.1 via cardinal-components
	- cardinal-components-chunk 5.0.1 via cardinal-components
	- cardinal-components-entity 5.0.1 via cardinal-components
	- cardinal-components-item 5.0.1 via cardinal-components
	- cardinal-components-level 5.0.1 via cardinal-components
	- cardinal-components-scoreboard 5.0.1 via cardinal-components
	- cardinal-components-world 5.0.1 via cardinal-components
	- carrier 1.11.0
	- castle_dungeons 3.3-1.19-fabric
	- cauldronlib 1.2.2 via quicksand
	- cave_enhancements 1.2.8
	- cenchants 2.14.0
	- chalk 2.1.0+1.19
	- chalk-colorful-addon 2.1.0+1.19
	- chessmod 1.1.2
	- chestcavity 2.16.3
	- chisel 1.4.6
	- chord 1.8.0+1.19-fabric via wilderworld
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 7.0.73
	- cloth-config-lite 2.0.6 via mealapi
	- cloth-utils-v1 2.0.54 via computercraft
	- collective-fabric 4.27
	- colorfularmor 1.19-1.12
	- columns 1.5.1
	- com_electronwill_night-config_core 3.6.4 via terrablender
	- com_electronwill_night-config_toml 3.6.4 via terrablender
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_fasterxml_jackson_core_jackson-annotations 2.13.1 via spoornpacks
	- com_fasterxml_jackson_core_jackson-core 2.13.1 via spoornpacks
	- com_fasterxml_jackson_core_jackson-databind 2.13.1 via spoornpacks
	- com_github_llamalad7_mixinextras 0.0.11 via artifacts
	- com_typesafe_config 1.4.1 via croptopia
	- computercraft 1.101.0
	- conjuring 1.0.23+1.19
	- connectivity 1.19-3.2
	- continuity 2.0.0+1.19
	- cooldown-coordinator 0.4.2 via omnihopper
	- coralreef 1.19-1.0.1
	- crayfish 1.26.0 and 1.27.0
	- croptopia 2.0.7
	- crowdin-translate 1.4+1.19 via durabilityviewer
	- crusade 1.2.8
	- ctov 3.0
	- culinaire 2.5.0
	- curses 1.8.0
	- cyti 2.0.0
	- dawn 3.5.0
	- doom 4.2.7
	- dragonloot 1.1.1
	- dramaticdoors 1.19-1.2.0
	- drg_flares 1.2.3
	- ducts 1.1.8
	- dungeon_now_loading 1.0.0
	- dungeons_arise 2.1.51
	- durabilityviewer 1.19-fabric0.53.3-1.10.3
	- dyeable_shulkers 1.0.1
	- earthtojavamobs 1.9.2
	- ecologics 2.1.3
	- elementalswords 1.19-1.7.0-[FABRIC]
	- ellemes_container_lib 2.0.1
	- enchant_giver 1.3.0 via mcdw
	- enchanter 1.0
	- enchantmentsplus 1.1.0+1.19
	- enchdesc 11.0.5
	- end_origins 1.0.0
	- enderscape 0.3.4-1.19
	- exlinedoors 2.3.5
	- exlinefurniture 2.2.1
	- expandability 6.0.0 via artifacts
	- expandedstorage 8.0.1
	- explorerscompass 1.19-2.1.1-fabric
	- extra-enchantments-and-curses 1.4.1
	- extra_classes_origins 1.0.0
	- extraalchemy 1.8.3
	- extragenerators 1.2.1-BETA+1.19
	- fabric 0.57.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via fabric
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
	- fabric-blockrenderlayer-v1 1.1.18+9ff28f40a9 via fabric
	- fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
	- fabric-commands-v0 0.2.23+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.27+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.2.0+07df213ea9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.1.1+a680b9b4a9 via fabric
	- fabric-dimensions-v1 2.1.28+a6d2f785a9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.25+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.4+767db26ea9 via fabric
	- fabric-item-groups-v0 0.3.25+9ff28f40a9 via fabric
	- fabric-key-binding-api-v1 1.0.18+9ff28f40a9 via fabric
	- fabric-keybindings-v0 0.2.16+df3654b3a9 via fabric
	- fabric-language-kotlin 1.8.1+kotlin.1.7.0
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
	- fabric-loot-api-v2 1.1.0+03a4e568a9 via fabric
	- fabric-loot-tables-v1 1.1.3+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.10+33fbc738a9 via fabric
	- fabric-models-v0 0.3.15+9ff28f40a9 via fabric
	- fabric-networking-api-v1 1.0.27+7fe97409a9 via fabric
	- fabric-networking-v0 0.3.14+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.7+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via bewitchment
	- fabric-registry-sync-v0 0.9.17+23c4cfefa9 via fabric
	- fabric-renderer-api-v1 1.0.8+9ff28f40a9 via fabric
	- fabric-renderer-indigo 0.6.9+1f92344ea9 via fabric
	- fabric-renderer-registries-v1 3.2.18+df3654b3a9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-rendering-v0 1.1.20+df3654b3a9 via fabric
	- fabric-rendering-v1 1.10.14+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.5+a6d2f785a9 via fabric
	- fabric-screen-api-v1 1.0.24+f05effafa9 via fabric
	- fabric-screen-handler-api-v1 1.2.6+9ff28f40a9 via fabric
	- fabric-textures-v0 1.0.18+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabricaeexnihilo 0.1.6+mc1.19
	- fabricanvils 3.0.0
	- fabricenchantments 0.8.0
	- fabricloader 0.14.8
	- factory_blocks 1.0.0+1.19
	- fake-player-api 0.3.0 via the_bumblezone
	- farmersdelight 1.19-0.3.0
	- farmingforblockheads 11.0.1
	- fiber 0.23.0-2 via collective-fabric
	- fishofthieves 2.0.3
	- flytre_lib 1.8.8
	- forgero 0.9.3-BETA-1.19
	- frame 0.22.2+1.19
	- frame-api-base 0.2.0 via frame
	- frame-blocks-v0 0.1.2 via frame
	- frame-config-v0 0.2.1 via frame
	- frame-content-registries-v0 0.4.0+2876b511a9 via frame
	- frame-game-rules-v0 0.2.3 via frame
	- frame-items-v0 0.1.2 via frame
	- frame-loot-tables-v0 0.1.4 via frame
	- frame-rendering-v0 0.1.4 via frame
	- frame-tabbed-item-groups-v0 0.2.1 via frame
	- frame-toymaker-v0 0.6.0+c2d5b470a9 via frame
	- frame-woods-v0 0.1.0+ea73347fa9 via frame
	- friendsandfoes 1.5.5
	- fwaystones 3.0.2+mc1.19
	- gbfabrictools 1.3.4+1.19 via durabilityviewer
	- gearreborn 1.19-0.1.15
	- geckolib3 3.1.5
	- geodes 1.4.4
	- gobber2 2.6.21
	- goblintraders 1.5.2
	- graveyard 1.10
	- graveyard_biomes 1.2
	- grindenchantments 1.6.4+1.19
	- harvest_scythes 2.5.3
	- heartbond 1.4.0
	- hellish-materials 0.15.1
	- hollowwoods 1.2.1
	- hookshot 26.0
	- hwg 1.2.1
	- iconicwands 1.0.4
	- impersonate 2.6.0
	- imst 2.0.2
	- indium 1.0.6+mc1.19
	- io_leangen_geantyref_geantyref 1.3.11 via croptopia
	- io_netty_netty-codec-http 4.1.77.Final via computercraft
	- iris 1.2.5
	- jankson 4.1.1+j1.2.1 via libgui
	- java 17
	- kanos_config 0.3.1+1.14.4-1.19 via pehkui
	- kofitable 1.0.2+1.19
	- lambdynlights 2.1.2+1.19
	- libgui 6.0.0-beta.5+1.19-pre1 via additionaladditions
	- libninepatch 1.1.0 via libgui
	- libra 0.5.33
	- libraryferret 2.0.0
	- lithium 0.8.1
	- lootgoblins 1.0.8
	- magehand 1.1.2
	- magiccombatwands 1.0.2
	- magna 1.8.0-1.19 via modern_industrialization
	- majobroom 1.2.2
	- mavm 1.1.0
	- mcda 2.1.1
	- mcdar 1.5.0
	- mcdw 4.4.0-1.19
	- mcpitanlib 1.4.4 via advanced_reborn
	- mcsa 2.4.0-1.19
	- mcwbridges 2.0.3
	- mcwtrpdoors 1.0.6
	- mealapi 0.3.1+1.19
	- medievalorigins 1.19.x-4.1.2
	- medievalweapons 1.2.1
	- megane 8.1.0
	- megane-alloy-forgery 8.1.0 via megane
	- megane-api 8.1.0 via megane
	- megane-fabric-transfer 8.1.0 via megane
	- megane-reborn-core 8.1.0 via megane
	- megane-reborn-energy 8.1.0 via megane
	- megane-runtime 8.1.0 via megane
	- megane-tech-reborn 8.1.0 via megane
	- megane-vanilla 8.1.0 via megane
	- megaparrot 1.0.6
	- merenc 1.7
	- midnightlib 0.5.2
	- mimic 1.31
	- minecraft 1.19
	- minekea 3.2.0
	- mm 2.3 via friendsandfoes
	- mob_catcher 1.2.4
	- moborigins 1.9.0
	- modern_industrialization 1.3.1
	- modify-drops-api 0.4.0.2 via chestcavity
	- modmenu 4.0.4
	- moenchant_lib 0.5.1+1.19 via moenchantments
	- moenchantments 2.2.5+1.19
	- more_gems 1.4.26
	- moreberries 1.5.1
	- moremcmeta 1.19-3.0.4
	- morethanapickaxe 0.1.6c
	- morevillagers 4.0.2
	- mythicmetals 0.15.1
	- mythicmounts 1.19-7.0
	- naturalist 2.0.1
	- naturescompass 1.19-2.0.4-fabric
	- nears 1.2.2
	- neat 1.8-31-FABRIC
	- net_objecthunter_exp4j 0.4.8 via spoornarmorattributes
	- nicemod 1.1 - 1.19
	- no-telemetry 1.4.0
	- noindium 1.1.0+1.19 via modern_industrialization
	- notenoughcrashes 4.1.6+1.19
	- omega-config 1.2.2-1.18.1 via graveyard
	- omnihopper 1.1.3+1.19
	- online_detector 1.19-3.0.1
	- org_anarres_jcpp 1.4.14 via iris
	- org_jetbrains_kotlin_kotlin-reflect 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
	- org_joml_joml 1.10.4 via sodium
	- org_objenesis_objenesis 3.2 via plantinajar
	- org_spongepowered_configurate-core 4.1.2 via croptopia
	- org_spongepowered_configurate-hocon 4.1.2 via croptopia
	- org_squiddev_cobalt 0.5.5 via computercraft
	- origins 1.6.2
	- origins-classes 1.4.0
	- origins-plus-plus 1.6.2
	- originsumbrellas 1.5.3
	- overweight_farming 1.19-1.5.2-fabric
	- owo 0.7.3+1.19
	- oxidized 1.7.1
	- patchouli 1.19-74-FABRIC
	- peculiarpieces 1.1.0+1.19
	- pehkui 3.3.3+1.14.4-1.19.1
	- phosphor 0.8.1
	- physicsmod 2.8.1
	- plantinajar 2.4.1
	- playerabilitylib 1.6.0
	- plutoscoffee 1.19-1.9
	- pride 1.1.2+1.19 via lambdynlights
	- promenade 2.7.0
	- pugh_lib 1.4.10 via gobber2
	- pugh_tools 1.3.13 via gobber2
	- qu-enchantments 1.1.2-1.19
	- quarrymod 1.0.2
	- quicksand 1.2.1
	- random_ring 1.1.16
	- randombonemealflowers-fabric 1.8
	- rangers_haven 2.3.4
	- rare-ice 0.5.0
	- reach-entity-attributes 2.3.0 via besmirchment
	- reborncore 5.3.2 via techreborn
	- repurposed_structures 6.1.1+1.19
	- resourcechickens 1.19-Fabric-v1.0
	- resourceful_tools 1.3.15
	- ringsofascension 1.0
	- rocks 1.6.1
	- roughlyenoughitems 9.1.511
	- sandwichable 1.3.a+1.19
	- sculkhornid 0.1.1
	- sculksieg 1.0.0
	- simple_backpack 1.3.17
	- simpleteleporters 2.3.1
	- simply_houses 1.1.3-1.19
	- skylorlib 1.5.1
	- skyvillages 1.0.2.1
	- sodium 0.4.2+build.16
	- sonic_deflect 1.0.0+1.19
	- spellbound 1.9.2
	- spirit 2.1.2
	- splatus_spellbound_weapons 3.3.1
	- spoornarmorattributes 2.0.4-1.19
	- spoornpacks 4.3.1-1.19
	- spoornpink 3.4.2-1.19
	- spoornweaponattributes 4.0.6-1.19
	- spruceui 4.0.0+1.19 via lambdynlights
	- stacc 1.3.4 via bitsandchisels
	- step-height-entity-attribute 1.0.0 via artifacts
	- stoneholm 1.4.4
	- survivalplus 0.1.6f
	- taxfreelevels 1.3
	- team_reborn_energy 2.2.0 via cyti
	- techreborn 5.3.2
	- terrablender 2.0.0.117
	- terraform-shapes-api-v1 4.0.0 via promenade
	- terraform-wood-api-v1 4.1.0 via besmirchment
	- terramine 1.3.6+1.19
	- terrarianslimes 1.3-BETA+1.19
	- the_bumblezone 6.0.1+1.19
	- the_extractinator 1.10
	- things 0.2.19+1.19
	- thonkutil 2.15.3+1.19
	- thonkutil-base 1.13.1+575521ba57 via thonkutil
	- thonkutil-capes-v1 1.4.1+7ce8ef6257 via thonkutil
	- thonkutil-coords-v1 1.1.1+8ff533c957 via thonkutil
	- thonkutil-customization-v1 1.1.1+8ff533c957 via thonkutil
	- thonkutil-legacy 1.1.1+5d4263f557 via thonkutil
	- thonkutil-modchecker-v1 1.1.1+8ff533c957 via thonkutil
	- thonkutil-potions-v0 1.5.1+8ff533c957 via thonkutil
	- thonkutil-titlescreen-v1 1.2.1+8ff533c957 via thonkutil
	- thonkutil-trades-v1 1.2.1+8ff533c957 via thonkutil
	- tokenablefurnaces 2.0.1
	- toolleveling 1.19-1.3.3
	- toomanyorigins 0.6.3+1.19-fabric
	- torchbowmod 1.0
	- torcherino 17.0.1
	- travelersbackpack 1.19-8.0.1
	- tree-hollows 1.4
	- tree-hollows-core 1.4 via tree-hollows
	- treeaxe 1.2.14
	- trinkets 3.4.0
	- twigs 2.0.0-beta.8+1.19
	- utilities 1.5.3
	- visiblebarriers 1.5.2+1.19
	- vtaw_mw 1.0.0
	- wardenloot 1.0.9-1.19.x
	- warhammersmod 1.0.3
	- weird_equipment 0.8-beta
	- whisperwoods 1.19-2.1.0
	- wilderworld 2.3.0
	- woodenhoppers 1.3.1
	- wthit 5.6.1
	- xaerominimap 22.11.1
	- xaeroworldmap 1.25.1
	- xlpackets 2.1-1.17.1
	- xtraarrows 1.9.2
	- zihlaunchpads 1.2.0

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 7/14/22, 12:51 PM
Description: Unexpected error

java.lang.IllegalStateException: Pose stack not empty
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at net.minecraft.client.render.WorldRenderer.checkEmpty(WorldRenderer:1557)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1320)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1039)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:816)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1143)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:734)
	at net.minecraft.client.main.Main.main(Main:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_761.method_22979(class_761.java:1557)
	at net.minecraft.class_761.method_22710(class_761.java:1320)
	at net.minecraft.class_757.method_3188(class_757.java:1039)

-- Affected level --
Details:
	All players: 1 total; [class_746['Bullseye55'/213, l='ClientLevel', x=-1613.25, y=72.90, z=5673.20]]
	Chunk stats: 1024, 157
	Level dimension: minecraft:overworld
	Level spawn location: World: (-64,101,16), Section: (at 0,5,0 in -4,6,1; chunk contains blocks -64,-64,16 to -49,319,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 72049 game time, 72049 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:758)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by Virtuoel** [comment]
With the Pehkui 3.4.0 release, there should now be an error logged to the console if a rendering issue like this occurs with weird item rendering (I might look into making an error message for odd entity rendering issues later too).
Note that the message will be in the regular logs, not the crash log.

If this is in fact caused by item rendering, the message you'll want to look for will be in the log before the crash text, and is worded similarly to the following message with the `<...>`s replaced with the name of the item in question that was rendered strangely:
`[pehkui]: Was item rendering cancelled? Matrix stack not popped after rendering item <item.we_want_to.find_out> (<item_we_want_to_find_out>).`

If you run again with 3.4.0, have it crash, and then post your latest log from before the crash, I can (hopefully) narrow down the mods that may have caused the problem.

**Comment by Virtuoel** [comment]
Closing due to lack of response.

If the issue still occurs, leave a comment following the instructions I mentioned above about posting a `latest.log` (still applicable on latest Pehkui, not just on 3.4.0).

**Comment by Bullseye55** [comment]
Just got it again. Took a while, but, got it. Sending latest.log. This occurred on a creature death.

((Also, apologies. Completely forgot about this report due to life.))

[latest.log](https://github.com/Virtuoel/Pehkui/files/10365514/latest.log)

**Comment by Virtuoel** [comment]
Hmm, the debug info I added doesn't seem to be in that latest.log. Either this is a different issue that I don't have debug outputs for yet, or I accidentally made the info only show up in the crash report file and not the log file. Can you also post the corresponding crash log?

**Comment by Bullseye55** [comment]
[crash-2023-01-06_22.33.09-client.txt](https://github.com/Virtuoel/Pehkui/files/10367522/crash-2023-01-06_22.33.09-client.txt)
Here it is. Crashlog from the accompanying log.

**Comment by Virtuoel** [comment]
Hmm, this appears to be a different pose stack issue I've not yet accounted for in my debugging code. I'll have to investigate more closely. Thank you for the logs.

**Comment by Bullseye55** [comment]
No worries. Have e-mail notifications on this time, so, just update the issue if anything's found out. Not going to miss it(I hope!)

**Comment by Bullseye55** [comment]
Found the issue, but that world's as good as gone. Updating here for info.

https://www.curseforge.com/minecraft/mc-mods/haema is bundling an outdated 3.3.3 version of Pehkui in its 1.19 files that was hidden under my updated 3.6.3 version. Removed it now, likely will not run into this again.

**Comment by Fyoncle** [comment]
@Virtuoel I've gotten this issue on 1.21.1 Fabric
