### ISSUE TITLE
Server crashes when breeding sheep (or animals in general?)

### ISSUE THREAD

**Issue by HumanMint** [Virtuoel/Pehkui#30]
I updated recently to 1.7.0 and started to notice a weird bug with breeding sheep. As soon as one sheep successfully breeds it stops the server abruptly and shuts down the server. I noticed Pehkui referenced in the logs as the crash happened so I assumed this mod was the cause. I will share other parts of the logs when necessary.

[20:43:05] [Server thread/INFO]: HumanMint[/censored] logged in with entity id 148 at (-810.2237857201302, 66.03612159845635, -3.5700386965468796)
[20:43:06] [Server thread/INFO]: HumanMint joined the game
[20:43:06] [Server thread/INFO]: Sending config to HumanMint (a0d34995-cea3-46be-b2b6-c109cb682809)
[20:43:18] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to net.minecraft.class_1297
	at virtuoel.pehkui.util.ScaleUtils.loadAverageScales(ScaleUtils.java:41) ~[Pehkui-1.7.0+20w51a.jar:?]
	at net.minecraft.class_1429.handler$zca000$onBreed(class_1429.java:1021) ~[intermediary-server.jar:?]
	at net.minecraft.class_1429.method_24650(class_1429.java:238) ~[intermediary-server.jar:?]
	at net.minecraft.class_1341.method_6249(class_1341.java:79) ~[intermediary-server.jar:?]
	at net.minecraft.class_1341.method_6268(class_1341.java:60) ~[intermediary-server.jar:?]
	at net.minecraft.class_4135.method_6268(class_4135.java:55) ~[intermediary-server.jar:?]
	at net.minecraft.class_1355.tickGoals(class_1355.java:649) ~[intermediary-server.jar:?]
	at net.minecraft.class_1355.method_6275(class_1355.java:556) ~[intermediary-server.jar:?]
	at net.minecraft.class_1308.method_6023(class_1308.java:736) ~[intermediary-server.jar:?]
	at net.minecraft.class_1309.method_6007(class_1309.java:2508) ~[intermediary-server.jar:?]
	at net.minecraft.class_1308.method_6007(class_1308.java:542) ~[intermediary-server.jar:?]
	at net.minecraft.class_1296.method_6007(class_1296.java:127) ~[intermediary-server.jar:?]
	at net.minecraft.class_1429.method_6007(class_1429.java:54) ~[intermediary-server.jar:?]
	at net.minecraft.class_1472.method_6007(class_1472.java:138) ~[intermediary-server.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2254) ~[intermediary-server.jar:?]
	at net.minecraft.class_1308.method_5773(class_1308.java:342) ~[intermediary-server.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:621) ~[intermediary-server.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:561) ~[intermediary-server.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:411) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871) ~[intermediary-server.jar:?]
	... 5 more
[20:43:18] [Server thread/ERROR]: This crash report has been saved to: C:

**Comment by BeyJohn** [comment]
I am having the same problem with version 1.7.0, downgrading to version 1.6.2 does not crash in this scenario.
