### ISSUE TITLE
[Bug]: Pose Stack Not Empty Crash

### ISSUE THREAD

**Issue by fzzyhmstrs** [Virtuoel/Pehkui#303]
### Minecraft version(s)

1.18.2

### Mod loader

Fabric

### Mod loader version

0.14.8

### Fabric API version

0.58.0

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Game crashes when I am holding the _Glistering Trident_ item from [My Mod](https://github.com/fzzyhmstrs/ai) and I try to go into 3rd person with F5. This does not occur with a vanilla trident. This does not occur in first person.

This Trident uses the `BuiltinItemRendererRegistry.DynamicItemRenderer`

Game was an instance of the [Supercharged 5.0.1](https://modrinth.com/modpack/supercharged) modpack. Performed extensive mod-removal testing and no other mod seems to interact with the issue but _Pehkui_

same exception thrown as #299 

### Full list of installed mods

- additionalentityattributes 1.0.0+1.18.2 via spectrum
	- amecs 1.3.8+mc.1.18.2
	- amecsapi 1.3.5+mc22w06a via amecs
	- amethyst_core 0.2.0+1.18.2 via amethyst_imbuement
	- amethyst_imbuement 1.18.2-22
	- architectury 4.6.77
	- badpackets 0.1.2
	- badstdout 1.1.1-1.18
	- bannerpp 2.0.6-teb.1+mc.1.18.2 via spectrum
	- betterf3 1.2.5
	- blue_endless_jankson 1.2.1 via jankson
	- c2me 0.2.0+alpha.7.0
	- cardinal-components-base 4.1.3 via trinkets
	- cardinal-components-entity 4.1.3 via trinkets
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 6.2.62
	- cloth-config-lite 2.0.6 via mealapi
	- cloud 1.6.2 via terra
	- cloud_commandframework_cloud-brigadier_ 1.6.2 via cloud
	- cloud_commandframework_cloud-core_ 1.6.2 via cloud
	- cloud_commandframework_cloud-services_ 1.6.2 via cloud
	- cmods 1.2.0
	- coloredglowlib 1.3.0 via amethyst_imbuement
	- com_electronwill_night-config_core 3.6.5 via servercore
	- com_electronwill_night-config_toml 3.6.5 via servercore
	- com_github_llamalad7_mixinextras 0.0.10 via zoomify
	- com_ishland_c2me_libs_ 0.2.0+alpha.7.0 via c2me
	- config2brigadier 1.1.1 via simplevillagers
	- dev_isxander_settxi 2.1.1 via shotify
	- fabric 0.58.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.2+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.6+651bcc5960 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.23+d7c144a860 via fabric
	- fabric-content-registries-v0 3.1.1+c85f2e3860 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric
	- fabric-data-generation-api-v1 3.0.1+9fcb91d260 via fabric
	- fabric-dimensions-v1 2.1.20+489d6f8260 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.19+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.5.2+17cbbd4360 via fabric
	- fabric-item-groups-v0 0.3.14+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-language-kotlin 1.8.2+kotlin.1.7.10
	- fabric-lifecycle-events-v1 2.1.0+cc71601c60 via fabric
	- fabric-loot-api-v2 1.1.0+1997ad1260 via fabric
	- fabric-loot-tables-v1 1.1.2+e747827960 via fabric
	- fabric-mining-level-api-v1 2.1.4+cc71601c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.23+2d30af4b60 via fabric
	- fabric-networking-v0 0.3.10+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.3+032c981d60 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via universal-graves
	- fabric-registry-sync-v0 0.9.10+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.3+41a02c8a60 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.5.2+446e059560 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.2+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.3+f4563ac860 via fabric
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric
	- fabricloader 0.14.8
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via patchouli
	- graphlib 0.2.4+1.18.2 via wiredredstone
	- hologram-api 0.2.1+1.18-pre5 via universal-graves
	- incubus_core 1.7-rc.4 via spectrum
	- io_leangen_geantyref_geantyref 1.3.13 via cloud
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- kanos_config 0.3.1+1.14.4-1.19 via pehkui
	- lazydfu 0.1.2
	- libblockattributes_core 0.10.2 via libmultipart_deps_container
	- libgui 5.3.1+1.18 via qcraft
	- libmultipart 0.7.3-pre.4 via libmultipart_deps_container
	- libmultipart_deps_container 0.7.3-pre.4 via wiredredstone
	- libnetworkstack 0.6.0 via libmultipart_deps_container
	- libninepatch 1.1.0 via libgui
	- me_hypherionmc_simplerpc_simple-rpc-common 4.0.3 via simple-rpc
	- mealapi 0.3.1+1.18.2
	- minecraft 1.18.2
	- modmenu 3.2.3
	- mostructures 1.4.2+1.18.2
	- omega-config 1.2.3-1.18.1 via mostructures
	- optigui 1.1.0
	- org_apache_commons_commons-text 1.9 via optigui
	- org_bundleproject_libversion 0.0.3 via shotify
	- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
	- owo 0.7.2+1.18
	- packet_tweaker 0.3.0+1.18.2 via polymer
	- patchouli 1.18.2-71-FABRIC
	- pehkui 3.3.3+1.14.4-1.19.1
	- perspektive 1.0.2
	- placeholder-api 1.1.3+1.17.1 via universal-graves
	- playerabilitylib 1.5.0 via amethyst_imbuement
	- polymer 0.2.0-rc.4.2+1.18.2 via polymer-all
	- polymer-all 0.2.0-rc.4.2+1.18.2
	- polymer-blocks-ext 0.1.0-alpha.7+1.18.2 via polymer-all
	- polymer-legacy 0.1.9+0.2.0-rc.4.2+1.18.2 via polymer
	- qcraft 1.0.0
	- qu-enchantments 0.6.1-1.18.2
	- quickcraft 1.2.5
	- quickrepair 2.0.0-rc.2
	- rain-grow 1.0
	- raknetify 0.1.0+alpha.5.0
	- reaping 2.1.5
	- rebind_all_the_keys 1.1.1+1.18
	- right-click-harvest 1.2.0
	- roughlyenoughitems 8.3.510
	- sandwichable 1.3+1.18.2
	- satin 1.7.2 via spectrum
	- server_translations_api 1.4.12+1.18.2 via universal-graves
	- servercore 1.2.9-1.18.2
	- settxicloth 1.0.2 via zoomify
	- sgui 1.0.2+1.18.2 via universal-graves
	- shotify 1.1.0
	- shwfox 1.3+fabric
	- simple-rpc 3.1.1
	- simplevillagers 1.2.2
	- simply_houses 1.1.0
	- sleepwarp 1.1.1+1.18.2
	- spectrum 1.4.2-1.18.2-chaos_and_exploration
	- spruceui 3.3.1+1.17 via sandwichable
	- starlight 1.0.2+fabric.89b8d9f
	- statuseffecttimer 1.1.1+1.18.1
	- step-height-entity-attribute 1.0.0 via spectrum
	- structurized-reborn 1.18.2-01 via amethyst_imbuement
	- subterrestrial 1.0.2
	- suggestion_tweaker 1.18.2-1.2.0
	- tatercart 1.0.0-pre.4+1.18.2
	- taxfreelevels 1.3
	- team_reborn_energy 2.2.0 via wiredredstone
	- terra 6.0.0-BETA+a9248435a
	- tooltipfix 1.0.4-1.18
	- toomanybinds 0.3.2+1.18.2
	- toomanybinds-compat-1-16 0.3.2+1.16 via toomanybinds-compat-1-17
	- toomanybinds-compat-1-17 0.3.2+1.17 via toomanybinds-compat-1-18-2
	- toomanybinds-compat-1-18-2 0.3.2+1.18.2 via toomanybinds-compat-1-19
	- toomanybinds-compat-1-19 0.3.2+1.19 via toomanybinds
	- toomanybinds-core 0.3.2 via toomanybinds-compat-1-16
	- trinkets 3.3.1
	- uiinputundo 1.2.0
	- ultimatetool 1.0.0
	- universal-graves 2.0.3+1.18.2
	- vmp 0.2.0+beta.3.69
	- voidcrafting 1.6.4+fabric-1.18.2
	- vt_downloader 1.0.6+1.18
	- wagyourminimap 1.0.9+1.18.2-fabric
	- whyamionfire 1.1.2
	- wiredredstone 0.3.6+1.18.2
	- wthit 4.11.0
	- yosbr 0.1.1
	- zoomify 1.6.0

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Truncated crash report output:</summary>
<p>
MultiMC version: 0.6.16-3431

.........

.........

[18:40:59] [Render thread/INFO]: Loaded 16 advancements
[18:41:00] [Render thread/WARN]: Shader 953babc61b7d3bc9bfd95a62e6dc933dc8629aeb could not find uniform named subpixel_amount in the specified shader program.
[18:41:02] [Server thread/INFO]: Saving and pausing game...
[18:41:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[18:41:02] [Server thread/INFO]: Saving block-graph for 'ServerLevel[New World]'/minecraft:overworld
[18:41:04] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[18:41:04] [Server thread/INFO]: Saving block-graph for 'ServerLevel[New World]'/minecraft:the_nether
[18:41:04] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/spectrum:deeper_down_dimension
[18:41:04] [Server thread/INFO]: Saving block-graph for 'ServerLevel[New World]'/spectrum:deeper_down_dimension
[18:41:04] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[18:41:04] [Server thread/INFO]: Saving block-graph for 'ServerLevel[New World]'/minecraft:the_end
[18:41:04] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2869ms or 57 ticks behind
[18:41:30] [Render thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[18:41:30] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.class_761.method_22979(class_761.java:1553) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1316) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1034) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:813) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1122) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[18:41:31] [Server thread/INFO]: Stopping server
[18:41:31] [Server thread/INFO]: Saving players
[18:41:31] [Server thread/INFO]: Sigh_McGuy lost connection: Disconnected
[18:41:31] [Server thread/INFO]: Sigh_McGuy left the game
[18:41:31] [Server thread/INFO]: Stopping singleplayer server as player logged out
[18:41:31] [Server thread/INFO]: Saving worlds
[18:41:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[18:41:31] [Server thread/INFO]: Saving block-graph for 'ServerLevel[New World]'/minecraft:overworld
[18:41:33] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[18:41:33] [Server thread/INFO]: Saving block-graph for 'ServerLevel[New World]'/minecraft:the_nether
[18:41:33] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/spectrum:deeper_down_dimension
[18:41:33] [Server thread/INFO]: Saving block-graph for 'ServerLevel[New World]'/spectrum:deeper_down_dimension
[18:41:33] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[18:41:33] [Server thread/INFO]: Saving block-graph for 'ServerLevel[New World]'/minecraft:the_end
[18:41:33] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World (2)): All chunks are saved
[18:41:33] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[18:41:33] [Server thread/INFO]: ThreadedAnvilChunkStorage (deeper_down_dimension): All chunks are saved
[18:41:33] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[18:41:33] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[18:41:33] [Server thread/INFO]: Saving block-graph for 'ServerLevel[New World]'/minecraft:overworld
[18:41:33] [Server thread/INFO]: Saving block-graph for 'ServerLevel[New World]'/minecraft:the_nether
[18:41:33] [Server thread/INFO]: Saving block-graph for 'ServerLevel[New World]'/spectrum:deeper_down_dimension
[18:41:33] [Server thread/INFO]: Saving block-graph for 'ServerLevel[New World]'/minecraft:the_end
[18:41:33] [Render thread/INFO]: exiting MapServer{server_slug='UNKNOWN_SERVER_NAME'}
---- Minecraft Crash Report ----
// Why did you do that?

Time: 7/26/22, 6:41 PM
Description: Unexpected error

java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.class_761.method_22979(class_761.java:1553)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_761.method_22979(class_761.java:1553)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1034)

-- Affected level --
Details:
	All players: 1 total; [class_746['Sigh_McGuy'/226, l='ClientLevel', x=-95.92, y=64.00, z=-186.83]]
	Chunk stats: 961, 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (-96,64,-192), Section: (at 0,0,0 in -6,4,-12; chunk contains blocks -96,-64,-192 to -81,319,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 4997 game time, 4997 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, linuxmaid-totem, custom-splashtexts, technoblade-pig, Copper Legacy Pack.zip

......

**Comment by Virtuoel** [comment]
Looks like you're having your trident rendered by mixing into `BuiltinModelItemRenderer` with your `GlisteringTridentModelMixin`.
Instead of that, you should be using `BuiltinItemRendererRegistry.INSTANCE.register` to register your renderer.

**Comment by fzzyhmstrs** [comment]
My current versions do use the Registry. As you can see, that mixin is no longer in my source. Perhaps you found it in the remapped source?

![image](https://user-images.githubusercontent.com/72876796/181136122-2ea65f7e-d030-4934-a12e-86a74e0b5796.png)

I register it with Amethyst Core [HERE](https://github.com/fzzyhmstrs/ai/blob/master/src/main/kotlin/me/fzzyhmstrs/amethyst_imbuement/registry/RegisterItemModel.kt)

Which registers it via [HERE](https://github.com/fzzyhmstrs/ac/blob/master/src/main/kotlin/me/fzzyhmstrs/amethyst_core/registry/ItemModelRegistry.kt)

code snippet:
```
fun registerItemEntityModel(item: Item , renderer: BuiltinItemRendererRegistry.DynamicItemRenderer, layer: EntityModelLayer , classType : Class<out Model>){
        entityModelMap[item] = CustomItemEntityModelLoader(layer, classType)
        BuiltinItemRendererRegistry.INSTANCE.register(item, renderer)
    }
```

**Comment by Virtuoel** [comment]
Ah, good catch, it was the one in remappedSrc. I'd recommend gitignore-ing that folder.
I'll investigate further tomorrow.

**Comment by Dragonfly-Totem** [comment]
I _suspect_ that this has the same root cause as identified above, but I would like to add that this issue also occurs when placing a Glistering Trident into an Item Frame.  Testing indicated this specific incompatibility existing between Amethyst Imbuement v06 (the source of the Glistering Trident) and Pekhui v3.3.3

**Comment by Virtuoel** [comment]
After some testing, the issue is most likely caused by the inject cancellation [here](https://github.com/fzzyhmstrs/ac/blob/1.18.2/src/main/java/me/fzzyhmstrs/amethyst_core/mixins/ItemRendererMixin.java#L44) in AmethystCore.
Looking at some other mods that do similar custom models by injecting into `ItemRenderer`, seems they typically do `matrices.scale(0, 0, 0);` instead of cancelling.

I've also added some logging to Pehkui as of release 3.4.0 that logs a little info if this issue happens with another mods' item rendering in the future.
