### ISSUE TITLE
Pehkui not working w/ Origins & origins++ after 1.19.2

### ISSUE THREAD

**Issue by juva-duva** [Virtuoel/Pehkui#310]
### Minecraft version(s)

1.19.2

### Mod loader

Fabric

### Mod loader version

11.9

### Fabric API version

Fabric API 0.59.0

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

I've used the Origins mod along with origins++ and pehkui for a while now. After 1.19.1 & 1.19.2, I decided to upgrade so I could make a server (I've tried servers on 1.19 before and they didn't work) I tested out the updated mods on a singleplayer world; the first time I try, the game crashes before I actually enter the world. When I relaunch the game, the world is still there, but when I join it, Pehkui isn't working. 

### Full list of installed mods

- Origins-1.19-1.6.2.jar
- origins-plus-plus-1.6.2.jar (1.19)
- Pehkui-3.4.0+1.14.1-1.19.2.jar
- fabric-api-0.59.0+1.19.2.jar

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>
Time: 2022-08-10 21:04:09
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'int net.minecraft.class_2170.method_9249(net.minecraft.class_2168, java.lang.String)'
	at io.github.apace100.apoli.power.factory.action.EntityActions.lambda$register$15(EntityActions.java:235)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.factory.action.meta.AndAction.lambda$action$0(AndAction.java:14)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.apace100.apoli.power.factory.action.meta.AndAction.action(AndAction.java:14)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.origins.power.OriginsCallbackPower.onChosen(OriginsCallbackPower.java:24)
	at io.github.apace100.origins.component.OriginComponent.lambda$onChosen$0(OriginComponent.java:49)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.apace100.origins.component.OriginComponent.onChosen(OriginComponent.java:49)
	at io.github.apace100.origins.networking.ModPacketsC2S.lambda$chooseOrigin$0(ModPacketsC2S.java:50)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Virtuoel** [comment]
Not a Pehkui issue. Apoli doesn't appear to be updated for 1.19.1+ yet. Will be fixed on their end once https://github.com/apace100/apoli/pull/61 gets merged and Origins gets updated to include the new Apoli.

**Comment by juva-duva** [comment]
thank you
