### ISSUE TITLE
[Bug]: Pehkui with ArcLight

### ISSUE THREAD

**Issue by Adrigamer2950** [Virtuoel/Pehkui#316]
### Minecraft version(s)

1.19.2

### Mod loader

Forge

### Mod loader version

42.0.0

### In what environment did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

When I open my server with Arclight, Pehkui doesn't run and crashes my server.

### Full list of installed mods

Simple Voice Chat v2.3.6
CustomPlayerModels-1.19-0.4.8a

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

[20ago2022 14:17:02.253] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[20ago2022 14:17:02.606] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [io.izzel.arclight.common.mod.ArclightConnector]
[20ago2022 14:17:02.697] [main/INFO] [Arclight/]: Núcleo de mixin de Arclight añadido.
[20ago2022 14:17:02.701] [main/INFO] [Arclight/]: Optimización de mixin de Arclight añadida.
[20ago2022 14:17:02.725] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments [nogui]
[20ago2022 14:17:30.474] [main/INFO] [net.minecraft.util.datafix.DataFixers/]: Building unoptimized datafixer
[20ago2022 14:17:32.097] [main/FATAL] [mixin/]: Mixin apply failed pehkui.mixins.json:compat116plus.FireballEntityMixin -> net.minecraft.world.entity.projectile.LargeFireball: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Specified index 4 for @ModifyArg is invalid for args (Lnet/minecraft/world/level/Level;Lnet/minecraft/world/entity/Entity;DDDFZLnet/minecraft/world/level/Explosion$BlockInteraction;), expected F on net/minecraft/world/entity/projectile/LargeFireball::onOnCollisionCreateExplosionProxy [INJECT Applicator Phase -> pehkui.mixins.json:compat116plus.FireballEntityMixin -> Apply Injections ->  -> Inject -> pehkui.mixins.json:compat116plus.FireballEntityMixin->@ModifyArg::onOnCollisionCreateExplosionProxy(F)F]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Specified index 4 for @ModifyArg is invalid for args (Lnet/minecraft/world/level/Level;Lnet/minecraft/world/entity/Entity;DDDFZLnet/minecraft/world/level/Explosion$BlockInteraction;), expected F on net/minecraft/world/entity/projectile/LargeFireball::onOnCollisionCreateExplosionProxy [INJECT Applicator Phase -> pehkui.mixins.json:compat116plus.FireballEntityMixin -> Apply Injections ->  -> Inject -> pehkui.mixins.json:compat116plus.FireballEntityMixin->@ModifyArg::onOnCollisionCreateExplosionProxy(F)F]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.findArgIndex(ModifyArgInjector.java:158) ~[mixin-0.8.5.jar%2395!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.injectAtInvoke(ModifyArgInjector.java:113) ~[mixin-0.8.5.jar%2395!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.injection.invoke.InvokeInjector.inject(InvokeInjector.java:82) ~[mixin-0.8.5.jar%2395!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.inject(ModifyArgInjector.java:103) ~[mixin-0.8.5.jar%2395!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[mixin-0.8.5.jar%2395!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[mixin-0.8.5.jar%2395!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1355) ~[mixin-0.8.5.jar%2395!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051) ~[mixin-0.8.5.jar%2395!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[mixin-0.8.5.jar%2395!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar%2395!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar%2395!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar%2395!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar%2395!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar%2395!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar%2395!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar%2395!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar%2386!/:10.0.8+10.0.8+main.0ef7e830] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2386!/:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2386!/:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2386!/:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at net.minecraft.world.entity.EntityType.<clinit>(EntityTypeMixin.java:206) ~[server-1.19.1-20220727.212338-srg.jar%23162!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:world.entity.EntityTypeMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.feature.MonsterRoomFeature.<clinit>(MonsterRoomFeature.java:26) ~[server-1.19.1-20220727.212338-srg.jar%23162!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.feature.Feature.<clinit>(Feature.java:81) ~[server-1.19.1-20220727.212338-srg.jar%23162!/:?] {re:classloading}
	at net.minecraft.data.worldgen.features.AquaticFeatures.<clinit>(AquaticFeatures.java:20) ~[server-1.19.1-20220727.212338-srg.jar%23162!/:?] {re:classloading}
	at net.minecraft.data.worldgen.features.FeatureUtils.m_236677_(FeatureUtils.java:24) ~[server-1.19.1-20220727.212338-srg.jar%23162!/:?] {re:classloading}
	at net.minecraft.data.BuiltinRegistries.m_236009_(BuiltinRegistries.java:87) ~[server-1.19.1-20220727.212338-srg.jar%23162!/:?] {re:classloading}
	at net.minecraft.data.BuiltinRegistries.m_236004_(BuiltinRegistries.java:114) ~[server-1.19.1-20220727.212338-srg.jar%23162!/:?] {re:classloading}
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?] {}
	at net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:113) ~[server-1.19.1-20220727.212338-srg.jar%23162!/:?] {re:classloading}
	at net.minecraft.core.Registry.<clinit>(Registry.java:665) ~[server-1.19.1-20220727.212338-srg.jar%23162!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.Bootstrap.m_135870_(BootstrapMixin.java:43) ~[server-1.19.1-20220727.212338-srg.jar%23162!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:server.BootstrapMixin,pl:mixin:A}
	at net.minecraft.server.Main.main(Main.java:110) ~[server-1.19.1-20220727.212338-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.1-42.0.0.jar%2398!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2386!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2386!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2386!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2386!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2386!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2386!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2386!/:?] {}
	at io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:41) [arclight-forge-1.19.1-1.0.0-SNAPSHOT.jar%2380!/:arclight-1.19.1-1.0.0-SNAPSHOT-8ed4ae1b] {}
	at io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:12) [arclight-forge-1.19.1-1.0.0-SNAPSHOT.jar%2380!/:arclight-1.19.1-1.0.0-SNAPSHOT-8ed4ae1b] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:23) [arclight-forge-1.19.1-1.0.0-SNAPSHOT.jar:arclight-1.19.1-1.0.0-SNAPSHOT-8ed4ae1b] {}
	at io.izzel.arclight.server.Launcher.main(Launcher.java:18) [arclight-forge-1.19.1-1.0.0-SNAPSHOT.jar:arclight-1.19.1-1.0.0-SNAPSHOT-8ed4ae1b] {}

**Comment by Adrigamer2950** [comment]
why do you close it?

**Comment by Adrigamer2950** [comment]
._.

**Comment by Virtuoel** [comment]
Because Pehkui 3.4.1 was released, which should fix this specific crash. If it still crashes with 3.4.1, please post a new crash log and I'll reopen this issue.

**Comment by Adrigamer2950** [comment]
still same error
![image](https://user-images.githubusercontent.com/58531641/186446030-9609aaf0-e34a-412f-8e7e-2714db5e4e4d.png)
