### ISSUE TITLE
[Bug]: ReachEntityAttributesMixin crashing the game on launch (net/minecraft/class_1309)

### ISSUE THREAD

**Issue by FLORIAN4600** [Virtuoel/Pehkui#394]
### Minecraft version(s)

1.16.5

### Mod loader

Fabric

### Mod loader version

0.14.18

### Fabric API version

0.42.0

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

I'm creating a mod, but since I updated to pehkui 3.7.x , my game crash when I try to launch it saying that some classes of minecraft can't be loaded and that the pehkui ReachEntityAttributesMixin is trying to load one of them.

### Full list of installed mods and their version numbers

Origins-1.16.5-0.7.3
fabric-api-0.42.0+1.16
Pehkui-3.7.2+1.14.4-1.19.4

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 01/04/2023 13:51
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'cardinal-components-entity'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_1922
		at java.base/java.lang.Class.forName0(Native Method)
		at java.base/java.lang.Class.forName(Class.java:466)
		at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
		at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1922
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
		... 14 more
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_1937
		at java.base/java.lang.Class.forName0(Native Method)
		at java.base/java.lang.Class.forName(Class.java:466)
		at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
		at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1937
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
		... 14 more
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_2960
		at net.fabricmc.fabric.impl.networking.NetworkingImpl.<clinit>(NetworkingImpl.java:40)
		at java.base/java.lang.Class.forName0(Native Method)
		at java.base/java.lang.Class.forName(Class.java:466)
		at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
		at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2960
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
		... 15 more
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_1657
		at java.base/java.lang.Class.forName0(Native Method)
		at java.base/java.lang.Class.forName(Class.java:466)
		at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
		at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1657
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
		... 14 more
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_2378
		at java.base/java.lang.Class.forName0(Native Method)
		at java.base/java.lang.Class.forName(Class.java:466)
		at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
		at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2378
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
		... 14 more
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_2960
		at net.fabricmc.fabric.api.event.Event.<clinit>(Event.java:63)
		at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:44)
		at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:63)
		at net.fabricmc.fabric.api.event.lifecycle.v1.ServerWorldEvents.<clinit>(ServerWorldEvents.java:32)
		at net.fabricmc.fabric.impl.structure.FabricStructureImpl.onInitialize(FabricStructureImpl.java:37)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2960
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
		... 14 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.fabricmc.fabric.impl.base.event.ArrayBackedEvent
		at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:44)
		at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:63)
		at net.fabricmc.fabric.impl.tool.attribute.ToolManagerImpl.<clinit>(ToolManagerImpl.java:92)
		at net.fabricmc.fabric.impl.tool.attribute.ToolHandlers.onInitialize(ToolHandlers.java:36)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_179
		at java.base/java.lang.Class.forName0(Native Method)
		at java.base/java.lang.Class.forName(Class.java:466)
		at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
		at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.class_179
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
		... 14 more
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_2960
		at virtuoel.pehkui.Pehkui.id(Pehkui.java:70)
		at virtuoel.pehkui.Pehkui.<clinit>(Pehkui.java:78)
		at java.base/java.lang.Class.forName0(Native Method)
		at java.base/java.lang.Class.forName(Class.java:466)
		at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
		at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2960
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
		... 16 more
	Suppressed: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'reach-entity-attributes'
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 8 more
	Caused by: java.lang.RuntimeException: Mixin transformation of com.jamieswhiteshirt.reachentityattributes.ReachEntityAttributes failed
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
		at java.base/java.lang.Class.forName0(Native Method)
		at java.base/java.lang.Class.forName(Class.java:466)
		at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
		at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
		... 9 more
	Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
		... 18 more
	Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [pehkui.mixins.json:reach.compat.ReachEntityAttributesMixin from mod pehkui] from phase [DEFAULT] in config [pehkui.mixins.json] FAILED during APPLY
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
		... 21 more
	Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> pehkui.mixins.json:reach.compat.ReachEntityAttributesMixin from mod pehkui -> Apply Methods -> (Lnet/minecraft/class_1309;DLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V:handler$zze000$pehkui$getBlockDistance -> Transform LVT -> var=entity -> desc=Lnet/minecraft/class_1309;]
		at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:510)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:535)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:521)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
		... 21 more
	Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: net.minecraft.class_1309
		at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:1002)
		at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:962)
		at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformLVT(MixinTargetContext.java:563)
		at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:469)
		... 28 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_1297
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1297
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1355008584 bytes (1292 MB) / 2122317824 bytes (2024 MB) up to 8552185856 bytes (8156 MB)
	CPUs: 12
	JVM Flags: 0 total; 
	Launched Version: Fabric
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: ~~ERROR~~ UnsatisfiedLinkError: Failed to locate library: lwjgl.dll
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by FLORIAN4600** [comment]
never mind, I put the whole src without the fabric.mod.json and the mixins.json into a fabric template, reconfigured manually all the settings and it worked.
It just says that net.minecraft.entity.damage.EntityDamageSource.method_5529() doesn't exists but it stopped crashing

**Comment by FLORIAN4600** [comment]
never mind, I put the whole src without the fabric.mod.json and the mixins.json into a fabric template, reconfigured manually all the settings and it worked (before posting the error here, I had already tried copying the gradle and fabric settings from a fabric template and deleting the .gradle and run folder but it didn't worked).
It just says that net.minecraft.entity.damage.EntityDamageSource.method_5529() doesn't exists but it stopped crashing
