### ISSUE TITLE
Crash when trying to add Pehkui as a dependency with Architectury Forge

### ISSUE THREAD

**Issue by dayofpi** [Virtuoel/Pehkui#419]
### Minecraft version(s)

1.19.3

### Mod loader

Forge

### Mod loader version

1.19.3-44.1.23

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

I tried to add Pehkui as a dependency but as soon as I load a world it crashes

### Full list of installed mods and their version numbers

Pehkui 3.7.5+1.19.3-forge
Caelus 1.19.4-3.0.0.10

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

---- Minecraft Crash Report ----
// My bad.

Time: 2023-06-13 11:48:32
Description: Exception ticking world

java.lang.NoSuchMethodError: 'void net.minecraft.server.level.ServerEntity.m_8538_(net.minecraft.network.protocol.Packet)'
	at net.minecraft.server.level.ServerEntity.handler$zbf000$pehkui$syncEntityData(ServerEntity.java:540) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:mixin,pl:unprotect:A,re:classloading,pl:mixin:APP:pehkui.mixins.json:EntityTrackerEntryMixin,pl:mixin:A,pl:unprotect:A}
	at net.minecraft.server.level.ServerEntity.sendDirtyEntityData(ServerEntity.java) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:mixin,pl:unprotect:A,re:classloading,pl:mixin:APP:pehkui.mixins.json:EntityTrackerEntryMixin,pl:mixin:A,pl:unprotect:A}
	at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:164) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:mixin,pl:unprotect:A,re:classloading,pl:mixin:APP:pehkui.mixins.json:EntityTrackerEntryMixin,pl:mixin:A,pl:unprotect:A}
	at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:1190) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:classloading,pl:unprotect:A}
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:377) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,pl:unprotect:A}
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:311) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,pl:unprotect:A}
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:289) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,pl:unprotect:A,re:mixin,pl:accesstransformer:B,pl:unprotect:A}
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:876) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,pl:unprotect:A}
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:816) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,pl:unprotect:A}
	at net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:85) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:classloading,pl:unprotect:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:664) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,pl:unprotect:A}
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:251) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,pl:unprotect:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.level.ServerEntity.handler$zbf000$pehkui$syncEntityData(ServerEntity.java:540) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:mixin,pl:unprotect:A,re:classloading,pl:mixin:APP:pehkui.mixins.json:EntityTrackerEntryMixin,pl:mixin:A,pl:unprotect:A}
	at net.minecraft.server.level.ServerEntity.sendDirtyEntityData(ServerEntity.java) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:mixin,pl:unprotect:A,re:classloading,pl:mixin:APP:pehkui.mixins.json:EntityTrackerEntryMixin,pl:mixin:A,pl:unprotect:A}
	at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:164) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:mixin,pl:unprotect:A,re:classloading,pl:mixin:APP:pehkui.mixins.json:EntityTrackerEntryMixin,pl:mixin:A,pl:unprotect:A}
	at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:1190) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:classloading,pl:unprotect:A}
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:377) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,pl:unprotect:A}
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:311) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,pl:unprotect:A}
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:289) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,pl:unprotect:A,re:mixin,pl:accesstransformer:B,pl:unprotect:A}
-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,69,0), Section: (at 0,5,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 33961 game time, 19939 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 46940 (now: false), thunder time: 39696 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:876) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,pl:unprotect:A}
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:816) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,pl:unprotect:A}
	at net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:85) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:classloading,pl:unprotect:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:664) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,pl:unprotect:A}
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:251) ~[forge-1.19.3-44.1.23-minecraft-project-@forge-merged-named.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,pl:unprotect:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.5, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Amazon.com Inc.
	Memory: 1033784224 bytes (985 MiB) / 2629828608 bytes (2508 MiB) up to 3160408064 bytes (3014 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
	Identifier: Intel64 Family 6 Model 126 Stepping 5
	Microarchitecture: Ice Lake (Client)
	Frequency (GHz): 1.19
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x8a56
	Graphics card #0 versionInfo: DriverVersion=30.0.101.3111
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 22294.08
	Virtual memory used (MB): 18005.37
	Swap memory total (MB): 10240.00
	Swap memory used (MB): 1287.63
	JVM Flags: 0 total; 
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:super_block_world, mod:caelus, mod:forge, mod:architectury (incompatible), mod:pehkui (incompatible), mod:generated_1cb8838 (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: MOD_DEV
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclientuserdev
	ModLauncher naming: mcp
	ModLauncher services: 
		mixin-patched-0.8.5.8.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.3-44.1.23.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.3-44.1.23.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.3-44.1.23.jar runtime_enum_extender PLUGINSERVICE 
		unprotect-1.2.0.jar unprotect PLUGINSERVICE 
		fmlloader-1.19.3-44.1.23.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.3-44.1.23.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar ForgeLoomMixinRemapperInjector TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		forge-1.19.3-44.1.23-minecraft-project-@forge-merg|Minecraft                     |minecraft                     |1.19.3              |DONE      |Manifest: NOSIGNATURE
		B385b185e5a03-B385b185e5a03.jar                   |Pehkui                        |pehkui                        |3.7.5+1.19.3-forge  |DONE      |Manifest: NOSIGNATURE
		main                                              |Super Block World             |super_block_world             |1.0.0+1.19.3        |DONE      |Manifest: NOSIGNATURE
		B69fce65adf28-B69fce65adf28.jar                   |Caelus API                    |caelus                        |1.19.4-3.0.0.10     |DONE      |Manifest: NOSIGNATURE
		                                                  |Forge                         |forge                         |44.1.23             |DONE      |Manifest: NOSIGNATURE
		B4646e172162f-B4646e172162f.jar                   |Architectury                  |architectury                  |7.1.78              |DONE      |Manifest: NOSIGNATURE
		15402914769144442128.jar                          |generated_1cb8838             |generated_1cb8838             |1                   |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 2d16d5c4-0973-43ab-bcfb-570d3ea8b747
	FML: 44.1
	Forge: net.minecraftforge:44.1.23

**Comment by Virtuoel** [comment]
Strange, seems as if something didn't get remapped for some reason. Can you post the contents of your `build.gradle`?

**Comment by dayofpi** [comment]
plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
}

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

repositories {
    maven {
        url = "https://maven.theillusivec4.top/"
    }

    maven {
        url = "https://jitpack.io"
    }
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

dependencies {
    forge "net.minecraftforge:forge:${rootProject.forge_version}"

    modApi "dev.architectury:architectury-forge:${rootProject.architectury_version}"

    modApi("com.github.Virtuoel:Pehkui:3.7.5-1.19.3-forge")

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive = false }

    modImplementation "top.theillusivec4.caelus:caelus-forge:1.19.4-3.0.0.10"
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }
}

shadowJar {
    exclude "fabric.mod.json"

    configurations = [project.configurations.shadowCommon]
    classifier "dev-shadow"
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    classifier null
}

jar {
    classifier "dev"
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenForge(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + project.name
            from components.java
        }
    }

    repositories {
    }
}

**Comment by Virtuoel** [comment]
Can you test again with the Pehkui 3.7.6 release? If the problem still occurs, please also post your root build.gradle and gradle.properties (or alternatively a github repo of your project would be helpful for me to better investigate this issue).

**Comment by dayofpi** [comment]
I tested it with 3.7.6 and it still crashed. Here's the repo https://github.com/dayofpi/super-block-world-architectury

**Comment by Virtuoel** [comment]
Should now be resolved as of Pehkui 3.7.7.
