### ISSUE TITLE
Crashing upon world loading, both on servers and on singleplayer world

### ISSUE THREAD

**Issue by SpotTheWolf1** [Virtuoel/Pehkui#430]
### Minecraft version(s)

1.20.1

### Mod loader

Forge

### Mod loader version

Forge 1.20.1 - 47.1.1

### In what kind of world or server did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

Upon startup, my Shockbyte server and my own singleplayer worlds crash when Pehkui is installed. I made sure it wasn't my other mods or mod overload by process of elimination, so I am 100% certain Pehkui was causing the issue. The server was previously on version 1.19.4 with the same mod list and it never had any issues. I'd like to see this resolved, since I use Pehkui alongside Customizable Player Models.

### Full list of installed mods and their version numbers

CreativeCore_FORGE_V2.10.26_mc1.20.1.Jar

Croptopia-1.20-FORGE-2.3.1.Jar

CustomPlayerModels-1.20-0.6.9a.jar

EnhancedVisuals_FORGE_V1.6.6_mc1.20.Jar

FallingTree-1.20.1-4.2.0.jar

ItemPhysic_FORGE_V1.6.9_mc1.20.jar

Patchouli-1.20.1-80-FORGE.jar

Pehkui-3.7.6+1.20.1-forge.jar

SmartBrainLib-forge-1.20-1.11.jar

[1.20.1]+SecurityCraft+v1.9.7-beta1.jar

appleskin-forge-mc1.20.1-2.5.0.jar

architectury-9.1.10-forge.Jar

balm-forge-1.20-7.0.4.jar

camera-1.20.1-1.0.4.jar

cfm-forge-1.20.1-7.0.0-pre36.Jar

curios-forge-5.2.0-beta.3+1.20.1.jar

dynamiclights-1.20.1.0.jar

geckolib-forge-1.20.1-4.2.1.jar

jei-1.20.1-forge-15.2.0.22.jar

minecraft-comes-alive-7.5.3+1.20.1-universal.jar

modonomicon-1.20.1-1.37.0.jar

occultism-1.20.1-1.81.0.Jar

soundphysics-forge-1.20.1-1.1.1.jar

timecontrol-1.20.1-1.4.0.jar

waystones-forge-1.20-14.0.0.jar

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2023-07-11 15:44:37
Description: Exception in server tick loop

java.lang.IllegalArgumentException: 'material' is an invalid type
	at team.creative.creativecore.common.util.ingredient.CreativeIngredient.load(CreativeIngredient.java:63) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.util.ingredient.CreativeIngredient$1.readElement(CreativeIngredient.java:115) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.util.ingredient.CreativeIngredient$1.readElement(CreativeIngredient.java:109) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeConveration$SimpleConfigTypeConveration.readElement(ConfigTypeConveration.java:923) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeList.readElement(ConfigTypeList.java:44) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeList.readElement(ConfigTypeList.java:29) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeConveration.read(ConfigTypeConveration.java:188) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.holder.ConfigHolder.load(ConfigHolder.java:121) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.holder.ConfigHolderObject.load(ConfigHolderObject.java:65) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeConveration$9.readElement(ConfigTypeConveration.java:741) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeConveration$9.readElement(ConfigTypeConveration.java:736) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeConveration.read(ConfigTypeConveration.java:188) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.holder.ConfigHolder.load(ConfigHolder.java:121) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.holder.ConfigHolderObject.load(ConfigHolderObject.java:65) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeConveration$9.readElement(ConfigTypeConveration.java:741) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeConveration$9.readElement(ConfigTypeConveration.java:736) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.converation.ConfigTypeConveration.read(ConfigTypeConveration.java:188) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.holder.ConfigHolder.load(ConfigHolder.java:121) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.holder.ConfigHolderObject.load(ConfigHolderObject.java:65) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.event.ConfigEventHandler.load(ConfigEventHandler.java:225) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.event.ConfigEventHandler.load(ConfigEventHandler.java:238) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.event.ConfigEventHandler.startServer(ConfigEventHandler.java:87) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading}
	at team.creative.creativecore.common.config.event.__ConfigEventHandler_startServer_ServerAboutToStartEvent.invoke(.dynamic) ~[CreativeCore_FORGE_v2.10.26_mc1.20.1.jar%23192!/:2.10.26] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:99) ~[forge-1.20.1-47.1.0-universal.jar%23219!/:?] {re:classloading}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23214!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 537736512 bytes (512 MiB) / 1644167168 bytes (1568 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce RTX 3050 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x25a5
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6262
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9bc4
	Graphics card #1 versionInfo: DriverVersion=27.20.100.8280
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 22871.05
	Virtual memory used (MB): 15589.85
	Swap memory total (MB): 14848.00
	Swap memory used (MB): 1385.19
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:cpm (incompatible), mod:pehkui (incompatible), mod:forge, mod:sound_physics_remastered, mod:appleskin (incompatible), mod:creativecore, mod:itemphysic, mod:dynamiclights (incompatible), mod:architectury (incompatible), mod:mca (incompatible), mod:balm, mod:patchouli (incompatible), mod:waystones, mod:croptopia (incompatible), mod:cfm, mod:jei, mod:smartbrainlib (incompatible), mod:modonomicon, mod:geckolib, mod:occultism, mod:curios (incompatible), mod:camera, mod:securitycraft, mod:timecontrol, mod:fallingtree (incompatible), mod:enhancedvisuals, mod:flywheel, mod:create
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: 1.20.1-forge-47.1.0
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.1.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.1.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.1.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		SmartBrainLib-forge-1.20-1.11.jar                 |SmartBrainLib                 |smartbrainlib                 |1.11                |DONE      |Manifest: NOSIGNATURE
		timecontrol-1.20.1-1.4.0.jar                      |TimeControl                   |timecontrol                   |1.4.0               |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.20.1-4.2.1.jar                   |GeckoLib 4                    |geckolib                      |4.2.1               |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.10.26_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.10.26             |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.22.jar                    |Just Enough Items             |jei                           |15.2.0.22           |DONE      |Manifest: NOSIGNATURE
		Pehkui-3.7.6+1.20.1-forge.jar                     |Pehkui                        |pehkui                        |3.7.6+1.20.1-forge  |DONE      |Manifest: NOSIGNATURE
		dynamiclights-1.20.1.0.jar                        |Dynamic Lights                |dynamiclights                 |1.20.1.0            |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.2.0-beta.3+1.20.1.jar              |Curios API                    |curios                        |5.2.0-beta.3+1.20.1 |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.20-0.6.9-4.jar                   |Flywheel                      |flywheel                      |0.6.9-4             |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.20.1-1.1.1.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.20.1-1.1.1        |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.20.1-80-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-80-FORGE     |DONE      |Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.d.jar                         |Create                        |create                        |0.5.1.d             |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.20-14.0.0.jar                   |Waystones                     |waystones                     |14.0.0              |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.20-FORGE-2.3.1.jar                    |Croptopia                     |croptopia                     |2.3.1               |DONE      |Manifest: NOSIGNATURE
		camera-1.20.1-1.0.4.jar                           |Camera Mod                    |camera                        |1.20.1-1.0.4        |DONE      |Manifest: NOSIGNATURE
		EnhancedVisuals_FORGE_v1.6.6_mc1.20.jar           |EnhancedVisuals               |enhancedvisuals               |1.6.6               |DONE      |Manifest: NOSIGNATURE
		[1.20.1]+SecurityCraft+v1.9.7-beta1.jar           |SecurityCraft                 |securitycraft                 |1.9.7-beta1         |DONE      |Manifest: NOSIGNATURE
		CustomPlayerModels-1.20-0.6.9a.jar                |Customizable Player Models    |cpm                           |0.6.9a              |DONE      |Manifest: NOSIGNATURE
		modonomicon-1.20.1-1.37.0.jar                     |Modonomicon                   |modonomicon                   |1.37.0              |DONE      |Manifest: NOSIGNATURE
		cfm-forge-1.20.1-7.0.0-pre36.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre36         |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		architectury-9.1.10-forge.jar                     |Architectury                  |architectury                  |9.1.10              |DONE      |Manifest: NOSIGNATURE
		minecraft-comes-alive-7.5.3+1.20.1-universal.jar  |Minecraft Comes Alive         |mca                           |7.5.3+1.20.1        |DONE      |Manifest: NOSIGNATURE
		occultism-1.20.1-1.81.0.jar                       |Occultism                     |occultism                     |1.81.0              |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20-7.0.4.jar                         |Balm                          |balm                          |7.0.4               |DONE      |Manifest: NOSIGNATURE
		ItemPhysic_FORGE_v1.6.9_mc1.20.jar                |ItemPhysic                    |itemphysic                    |1.6.9               |DONE      |Manifest: NOSIGNATURE
		FallingTree-1.20.1-4.2.0.jar                      |FallingTree                   |fallingtree                   |4.2.0               |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		forge-1.20.1-47.1.0-universal.jar                 |Forge                         |forge                         |47.1.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.20.1-2.5.0.jar                |AppleSkin                     |appleskin                     |2.5.0+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
	Flywheel Backend: GL33 Instanced Arrays
	Crash Report UUID: 279e0daf-b48e-422f-bcbf-365fe4bdec6a
	FML: 47.1
	Forge: net.minecraftforge:47.1.0

**Comment by Virtuoel** [comment]
The crash you posted is due to CreativeCore being outdated, not Pehkui.
However, Pehkui 3.7.6 with Forge on 1.20.1 is also known to crash. Be sure to also update Pehkui to 3.7.7.
