### ISSUE TITLE
[Bug]: p_130086_ is null while creating potion effect

### ISSUE THREAD

**Issue by fr1tZpapp0** [Virtuoel/Pehkui#444]
### Minecraft version(s)

1.19.2

### Mod loader

Forge

### Mod loader version

Forge 43.2.4

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Whilst creating a mod with a custom potion that will force the drinker / effected entity to shrink, When drinking the potion a bug occurs where the error is simply: "Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null"

I am unsure what this error means!

Any and all help is greatly appreciated!

### Full list of installed mods and their version numbers

Pehkui 3.77+1.19.2-Forge

And a custom written WIP 1.19.2 Forge mod that uses the Pehkui mod as a dependency

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

---- Minecraft Crash Report ----
// You're mean.

Time: 2023-08-14 00:30:48
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null
	at net.minecraft.network.FriendlyByteBuf.writeResourceLocation(FriendlyByteBuf.java:610) ~[forge-1.19.2-43.2.4_mapped_official_1.19.2-recomp.jar%23188!/:?] {re:classloading}
	at virtuoel.pehkui.network.ScalePacket.encode(ScalePacket.java:89) ~[Pehkui-3.7.7-1.19.2-forge_mapped_official_1.19.2.jar%23195!/:?] {re:classloading}
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryEncode$4(IndexedMessageCodec.java:121) ~[forge-1.19.2-43.2.4_mapped_official_1.19.2-recomp.jar%23187%23194!/:?] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryEncode(IndexedMessageCodec.java:119) ~[forge-1.19.2-43.2.4_mapped_official_1.19.2-recomp.jar%23187%23194!/:?] {re:classloading}
	at net.minecraftforge.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:134) ~[forge-1.19.2-43.2.4_mapped_official_1.19.2-recomp.jar%23187%23194!/:?] {re:classloading}
	at net.minecraftforge.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:68) ~[forge-1.19.2-43.2.4_mapped_official_1.19.2-recomp.jar%23187%23194!/:?] {re:classloading}
	at net.minecraftforge.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:81) ~[forge-1.19.2-43.2.4_mapped_official_1.19.2-recomp.jar%23187%23194!/:?] {re:classloading}
	at net.minecraftforge.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:112) ~[forge-1.19.2-43.2.4_mapped_official_1.19.2-recomp.jar%23187%23194!/:?] {re:classloading}
	at virtuoel.pehkui.util.ScaleUtils.syncScales(ScaleUtils.java:251) ~[Pehkui-3.7.7-1.19.2-forge_mapped_official_1.19.2.jar%23195!/:?] {re:mixin,re:classloading}
	at virtuoel.pehkui.util.ScaleUtils.syncScalesIfNeeded(ScaleUtils.java:215) ~[Pehkui-3.7.7-1.19.2-forge_mapped_official_1.19.2.jar%23195!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.level.ServerEntity.handler$zzn000$pehkui$syncEntityData(ServerEntity.java:540) ~[forge-1.19.2-43.2.4_mapped_official_1.19.2-recomp.jar%23188!/:?] {re:mixin,re:classloading,pl:mixin:APP:pehkui.mixins.json:EntityTrackerEntryMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerEntity.sendDirtyEntityData(ServerEntity.java) ~[forge-1.19.2-43.2.4_mapped_official_1.19.2-recomp.jar%23188!/:?] {re:mixin,re:classloading,pl:mixin:APP:pehkui.mixins.json:EntityTrackerEntryMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:159) ~[forge-1.19.2-43.2.4_mapped_official_1.19.2-recomp.jar%23188!/:?] {re:mixin,re:classloading,pl:mixin:APP:pehkui.mixins.json:EntityTrackerEntryMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:1180) ~[forge-1.19.2-43.2.4_mapped_official_1.19.2-recomp.jar%23188!/:?] {re:classloading}
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:376) ~[forge-1.19.2-43.2.4_mapped_official_1.19.2-recomp.jar%23188!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:310) ~[forge-1.19.2-43.2.4_mapped_official_1.19.2-recomp.jar%23188!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:285) ~[forge-1.19.2-43.2.4_mapped_official_1.19.2-recomp.jar%23188!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:866) ~[forge-1.19.2-43.2.4_mapped_official_1.19.2-recomp.jar%23188!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:806) ~[forge-1.19.2-43.2.4_mapped_official_1.19.2-recomp.jar%23188!/:?] {re:classloading,pl:accesstransformer:B}
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null

	at net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:84) ~[forge-1.19.2-43.2.4_mapped_official_1.19.2-recomp.jar%23188!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:654) ~[forge-1.19.2-43.2.4_mapped_official_1.19.2-recomp.jar%23188!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:244) ~[forge-1.19.2-43.2.4_mapped_official_1.19.2-recomp.jar%23188!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

**Comment by Virtuoel** [comment]
Some scale related entry from that custom written mod is missing an ID. Seems the mod didn't register its custom scale type, scale modifier, or whatever registrable Pehkui object it added.
