### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by cowdevs** [Virtuoel/Pehkui#47]
Whenever I try to scale myself with Immersive Portals the game crashes:

java.lang.NoSuchMethodError: virtuoel.pehkui.api.ScaleType.getScaleData(Lnet/minecraft/class_1297;)Lvirtuoel/pehkui/api/ScaleData;
	at com.qouteall.hiding_in_the_bushes.PehkuiInterfaceInitializer.onPlayerTeleportedClient(PehkuiInterfaceInitializer.java:46)
	at com.qouteall.hiding_in_the_bushes.PehkuiInterfaceInitializer$$Lambda$2478/123723853.accept(Unknown Source)
	at com.qouteall.immersive_portals.teleportation.ClientTeleportationManager.teleportPlayer(ClientTeleportationManager.java:212)
	at com.qouteall.immersive_portals.teleportation.ClientTeleportationManager.tryTeleport(ClientTeleportationManager.java:166)
	at com.qouteall.immersive_portals.teleportation.ClientTeleportationManager.manageTeleportation(ClientTeleportationManager.java:117)
	at net.minecraft.class_310.handler$zne000$onAfterClientTick(class_310.java:4916)
	at net.minecraft.class_310.method_1574(class_310.java:1583)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by Virtuoel** [comment]
Should now be resolved in 1.9.0.
