### ISSUE TITLE
[Bug]: mod crashes before it opens in forge in minecraft 1.65. 

### ISSUE THREAD

**Issue by vanx344** [Virtuoel/Pehkui#477]
### Minecraft version(s)

1.16.5

### Mod loader

Forge

### Mod loader version

36.2.39

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

when I put the Pehkui mod in multi mc launcher and launch the mod is not load at all. load

### Full list of installed mods and their version numbers

JujutsuCraft_1.16.5_ver19.jar
Pehkui-3.7.9+1.16.5-forge.jar
forge 36.2.39

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>
MultiMC version: 0.7.0-3814

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.33.146.124, 13.33.146.93, 13.33.146.33, 13.33.146.62]

session.minecraft.net resolves to:
    [2620:1ec:46::72, 2620:1ec:bdf::72, 13.107.213.72, 13.107.246.72]

textures.minecraft.net resolves to:
    [2620:1ec:bdf::48, 2620:1ec:46::48, 13.107.213.48, 13.107.246.48]

api.mojang.com resolves to:
    [2620:1ec:46::72, 2620:1ec:bdf::72, 13.107.246.72, 13.107.213.72]

Minecraft folder is:
/Applications/MultiMC.app/Data/instances/1.16.5/.minecraft

Java path is:
/Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home/bin/java

Checking Java version...
Java is version 20.0.2, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  /Applications/MultiMC.app/Data/instances/1.16.5/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  /Applications/MultiMC.app/Data/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /Applications/MultiMC.app/Data/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  /Applications/MultiMC.app/Data/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /Applications/MultiMC.app/Data/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /Applications/MultiMC.app/Data/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  /Applications/MultiMC.app/Data/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Applications/MultiMC.app/Data/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Applications/MultiMC.app/Data/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /Applications/MultiMC.app/Data/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar
  /Applications/MultiMC.app/Data/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  /Applications/MultiMC.app/Data/libraries/net/minecraftforge/forge/1.16.5-36.2.34/forge-1.16.5-36.2.34-launcher.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  /Applications/MultiMC.app/Data/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  /Applications/MultiMC.app/Data/libraries/cpw/mods/modlauncher/8.1.3/modlauncher-8.1.3.jar
  /Applications/MultiMC.app/Data/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
  /Applications/MultiMC.app/Data/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  /Applications/MultiMC.app/Data/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  /Applications/MultiMC.app/Data/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  /Applications/MultiMC.app/Data/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  /Applications/MultiMC.app/Data/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  /Applications/MultiMC.app/Data/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  /Applications/MultiMC.app/Data/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  /Applications/MultiMC.app/Data/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  /Applications/MultiMC.app/Data/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  /Applications/MultiMC.app/Data/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  /Applications/MultiMC.app/Data/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  /Applications/MultiMC.app/Data/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar
  /Applications/MultiMC.app/Data/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-macos.jar
  /Applications/MultiMC.app/Data/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar

Mods:
  [✔️] BiomesOPlenty-1.16.5-13.1.0.488-universal.jar
  [✔️] JujutsuCraft_1.16.5_ver19.jar
  [✔️] Pehkui-3.7.9+1.16.5-forge.jar
  [✔️] torohealth-1.16.4-forge-4.jar
  [✔️] Xaeros_Minimap_23.8.4_Forge_1.16.5.jar
  [✔️] XaerosWorldMap_1.36.0_Forge_1.16.5.jar

Params:
  --username Vanx69 --version 1.16.5 --gameDir /Applications/MultiMC.app/Data/instances/1.16.5/.minecraft --assetsDir /Applications/MultiMC.app/Data/assets --assetIndex 1.16 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release --launchTarget fmlclient --fml.forgeVersion 36.2.34 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: 1.16.5", -XstartOnFirstThread, -Xms512m, -Xmx1920m, -Duser.language=en]

Minecraft process ID: 844

Using onesix launcher.

Checking: MC_SLIM
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: PATCHED
Checking: MC_SRG
2023-11-26 10:13:53,030 main WARN Advanced terminal features are not available in this environment
[10:13:53] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Vanx69, --version, 1.16.5, --gameDir, /Applications/MultiMC.app/Data/instances/1.16.5/.minecraft, --assetsDir, /Applications/MultiMC.app/Data/assets, --assetIndex, 1.16, --uuid, <PROFILE ID>, --accessToken, ❄❄❄❄❄❄❄❄, --userType, msa, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.34, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --width, 854, --height, 480]
[10:13:53] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 20.0.2 by Oracle Corporation
[10:13:53] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[10:13:53] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/Applications/MultiMC.app/Data/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[10:13:54] [Thread-1/INFO] [STDERR/]: [org.lwjgl.system.ThreadLocalUtil:<clinit>:135]: [LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
[10:13:57] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.5, --gameDir, /Applications/MultiMC.app/Data/instances/1.16.5/.minecraft, --assetsDir, /Applications/MultiMC.app/Data/assets, --uuid, <PROFILE ID>, --username, Vanx69, --assetIndex, 1.16, --accessToken, ❄❄❄❄❄❄❄❄, --userType, msa, --versionType, release, --width, 854, --height, 480]
[10:14:00] [main/WARN] [mixin/]: Error loading class: java/util/Map$Entry (java.lang.IllegalArgumentException: Class file major version 64 is not supported by active ASM (version 9.0 supports class version 61), reading java.util.Map$Entry)
[10:14:00] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 64 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[10:14:00] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 64 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[10:14:00] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 64 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[10:14:00] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 64 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[10:14:00] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 64 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[10:14:00] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 64 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[10:14:00] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 64 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[10:14:00] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Class file major version 64 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.invoke.MethodHandles$Lookup)
[10:14:01] [pool-3-thread-1/WARN] [mixin/]: Error loading class: java/lang/Boolean (java.lang.IllegalArgumentException: Class file major version 64 is not supported by active ASM (version 9.0 supports class version 61), reading java.lang.Boolean)
[10:14:01] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:246]: Failed to start Minecraft:
[10:14:01] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: java.lang.reflect.InvocationTargetException
[10:14:01] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[10:14:01] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[10:14:01] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
[10:14:01] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[10:14:01] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[10:14:01] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
[10:14:01] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
[10:14:01] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[10:14:01] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:247]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: 	... 8 more
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: Caused by: java.lang.reflect.InvocationTargetException
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:673]: 	... 13 more
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:696]: Caused by: java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:696]: 	at net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:43)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:696]: 	at net.minecraft.client.main.Main.main(Main.java:123)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:696]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:lockedPrintStackTrace:696]: 	... 16 more
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:33)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:729)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: java.lang.Boolean
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:754)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:739)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:310)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[10:14:01] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:737]: 	... 24 more
[10:14:01] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
Process exited with exit code 255 (0xff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 26 Nov 2023 10:16:35 +0530

**Comment by Virtuoel** [comment]
The version of Java you're running the game with appears to be too new (Java 20.0.2). Minecraft 1.16.5 with mods does not support Java this new. This version usually best runs with Java 8.
