### ISSUE TITLE
[Bug]: Full Game Crash on Run

### ISSUE THREAD

**Issue by TheRanTan** [Virtuoel/Pehkui#563]
### Minecraft version(s)

1.18.2

### Minecraft version details

1.18.2

### Mod loader

Forge

### Mod loader version

forge 40.2.0

### In what kind of world or server did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

I am using a compiled modpack, and got a crash log pointing to Pehkui. After disabling the mod, the pack loaded with no issue.

### Full list of installed mods and their version numbers

archarsenal-1.18.2-1.1.jar
architectury-4.12.94-forge.jar
armourersworkshop-forge-1.18.2-2.1.4.jar
arsarsenal-1.0.5-1.18.2.jar
ars_elemental-1.18.2-0.4.9.9.jar
ars_nouveau-1.18.2-2.9.0.jar
AutoRegLib-1.7-53.jar
awesomedungeonnether-forge-1.18.2-3.1.1.jar
badpackets-forge-0.1.3.jar
balm-3.2.6.jar
bdlmod-1.18.2-1.2.1.jar
Better Cave Dweller-1.18.2.jar
bettercombat-forge-1.6.2+1.18.2.jar
BiomesOPlenty-1.18.2-16.0.0.134.jar
BloodMagic-1.18.2-3.2.6-41.jar
blueprint-1.18.2-5.5.0.jar
blue_skies-1.18.2-1.3.12.jar
Bookshelf-Forge-1.18.2-13.3.56.jar
born_in_chaos_[Forge]1.18.2_1.17.jar
Botania-1.18.2-435.jar
caelus-forge-1.18.1-3.0.0.2.jar
cfm-7.0.0-pre35-1.18.2.jar
citadel-1.11.3-1.18.2.jar
cloth-config-6.5.133-forge.jar
CNB-1.18.2-1.5.3.jar
CosmeticArmorReworked-1.18.2-v2a.jar
cristellib-forge-1.0.0.jar
ctov-2.9.4.jar
curios-forge-1.18.2-5.0.9.2.jar
CyclopsCore-1.18.2-1.17.10.jar
darkness-forge-mc118-2.0.91.jar
deeper_oceans-1.18.2-v1-0-1.jar
DoggyTalents-1.18.2-2.5.11.jar
druidcraftrg-0.0.12.jar
DungeonsArise-1.18.2-2.1.52-release.jar
emotecraft-for-MC1.18.2-2.2.7-b.build.50-forge.jar
enchanted-1.18.2-1.1.6.jar
Entity_Collision_FPS_Fix-forge-1.18.2-1.0.0.jar
EverlastingAbilities-1.18.2-1.8.2.jar
Fastload-Reforged-mc1.18.2-3.4.0.jar
firearrows-1.18.2-12-forge.jar
FramedBlocks-5.11.5.jar
geckolib-forge-1.18-3.0.57.jar
gpumemleakfix-1.18.2-1.6.jar
hardcorerevival-forge-1.18.2-8.0.1.jar
HealingShots1.1.jar
iceandfire-2.1.13-1.18.2-beta-3.jar
immersive_paintings-0.6.7+1.18.2-forge.jar
Incendium_1.18.2_v5.0.8.jar
InvView_Forge-1.3.0-1.18.2.jar
jei-1.18.2-forge-10.2.1.1009.jar
journeymap-1.18.2-5.9.8-forge.jar
JustEnoughResources-1.18.2-0.14.1.171.jar
knightcore-1.18.2-1.1.jar
lazydfu-1.0-1.18+.jar
libraryferret-forge-1.18.2-4.0.0.jar
LibX-1.18.2-3.2.18.jar
localizedchat-1.18-4.1.7.jar
Mantle-1.18.2-1.9.50.jar
ModListCrashReportP.txt
modonomicon-1.18.2-1.33.1.jar
MorePlayerModels-1.18.2.20240405.jar
MoreVanillaArmor-1.18.2-3.1.3.jar
MythicBotany-1.18.2-2.1.14.jar
occultism-1.18.2-1.84.0.jar
Patchouli-1.18.2-71.1.jar
Pehkui-3.8.2+1.18.2-forge.jar
player-animation-lib-forge-1.0.2+1.18.jar
polymorph-forge-1.18.2-0.50.jar
Runelic-Forge-1.18.2-11.0.1.jar
selene-1.18.2-1.17.16.jar
simplyswords-forge-1.40-1.18.2.jar
SmartBrainLib-forge-1.18.2-1.9.jar
SoMSecondSemester1.18.2-3.1.3.jar
sophisticatedbackpacks-1.18.2-3.20.3.1063.jar
sophisticatedcore-1.18.2-0.6.4.604.jar
soundphysics-forge-1.18.2-1.0.6.jar
StateObserver-forge-1.18.2-1.2.1.jar
structure_gel-1.18.2-2.4.8.jar
supplementaries-1.18.2-1.5.18.jar
TerraBlender-forge-1.18.2-1.2.0.126.jar
Terralith_1.18.2_v2.2.6.jar
timeout_fixes-1.18.1-1.0.0.jar
toomanyglyphs-1.18.1-2.0.7.15321.jar
twilightforest-1.18.2-4.1.1494-universal.jar
upgrade_aquatic-1.18.2-4.0.0.jar
voicechat-forge-1.18.2-2.5.25.jar
whisperwoods-1.18.2-2.1.0-forge.jar
wildbackport-1.2.3.jar
worldedit-mod-7.2.10.jar
zmedievalmusic-1.18.2-1.4.jar

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

14:48:33.849
mixin
main
Mixin apply failed pehkui.mixins.json:LivingEntityMixin -> net.minecraft.world.entity.LivingEntity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on pehkui.mixins.json:LivingEntityMixin->@Inject::pehkui$tickMovement$minVelocity(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/world/phys/Vec3;)V! Expected (Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/world/phys/Vec3;)V [INJECT Applicator Phase -> pehkui.mixins.json:LivingEntityMixin -> Apply Injections ->  -> Inject -> pehkui.mixins.json:LivingEntityMixin->@Inject::pehkui$tickMovement$minVelocity(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/world/phys/Vec3;)V]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on pehkui.mixins.json:LivingEntityMixin->@Inject::pehkui$tickMovement$minVelocity(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/world/phys/Vec3;)V! Expected (Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/world/phys/Vec3;)V [INJECT Applicator Phase -> pehkui.mixins.json:LivingEntityMixin -> Apply Injections ->  -> Inject -> pehkui.mixins.json:LivingEntityMixin->@Inject::pehkui$tickMovement$minVelocity(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/world/phys/Vec3;)V]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:517)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:447)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1355)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:116)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/patchouli@1.18.2-71.1/vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.SystemReport.handler$bel000$patchouli_addContext(SystemReport.java:516)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.SystemReport.<init>(SystemReport.java:57)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.CrashReport.<init>(CrashReport.java:29)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.CrashReport.m_127529_(CrashReport.java:213)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:137)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
14:48:34.496
launcher
main

Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:116)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/patchouli@1.18.2-71.1/vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.SystemReport.handler$bel000$patchouli_addContext(SystemReport.java:516)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.SystemReport.<init>(SystemReport.java:57)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.CrashReport.<init>(CrashReport.java:29)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.CrashReport.m_127529_(CrashReport.java:213)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:137)
	... 13 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [pehkui.mixins.json:LivingEntityMixin] from phase [DEFAULT] in config [pehkui.mixins.json] FAILED during APPLY
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 40 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on pehkui.mixins.json:LivingEntityMixin->@Inject::pehkui$tickMovement$minVelocity(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/world/phys/Vec3;)V! Expected (Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/world/phys/Vec3;)V [INJECT Applicator Phase -> pehkui.mixins.json:LivingEntityMixin -> Apply Injections ->  -> Inject -> pehkui.mixins.json:LivingEntityMixin->@Inject::pehkui$tickMovement$minVelocity(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/world/phys/Vec3;)V]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:517)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:447)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1355)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 40 more
14:48:34.496
monitor
Process Monitor
Process crashed with exit code 1

**Comment by TheRanTan** [comment]
Caused by spoungepowered shader pack
