### ISSUE TITLE
Not Working With Minecraft

### ISSUE THREAD

**Issue by Cheez409** [Virtuoel/Pehkui#67]
Every time I load this mod It crashes Minecraft According to the crash report

**Comment by Virtuoel** [comment]
Please upload your crash report. Without it I have no idea what could be causing your crash.

**Comment by Cheez409** [comment]
Caused by: java.lang.ClassNotFoundException: The specified mixin 'virtuoel.pehkui.mixin.AbstractDonkeyEntityMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1297) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:848) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	... 15 more

**Comment by Virtuoel** [comment]
Hmm, I thought I fixed this already. What version of Pehkui are you using?

**Comment by Cheez409** [comment]
https://github.com/Virtuoel/Pehkui/releases/tag/1.6.2%2B1.16.3

**Comment by Virtuoel** [comment]
That explains it. That version's very old and doesn't have the fix for that issue. The latest (1.10.0) is compatible with all versions from 1.14.4 up to the 1.17 snapshots.
