### ISSUE TITLE
[Fabric] Width & Height 0 bans players, crashes nearby clients and crashes the server

### ISSUE THREAD

**Issue by mikaib** [Virtuoel/Pehkui#79]
Easy to re-create.

set height to 0
set width to 0

And tada!

**Comment by Martinko366** [comment]
Ye, I actually have the same problem, idk how to fix it, one the player join, server will instantly crash.

**Comment by pengolod** [comment]
I have a similar problem - when https://github.com/Jack-Sibley/slimeorigin/issues/5 shrinks down too small, I get a reflection error?

<details>
<summary>Crash Report</summary>
<pre>
<code>
java.lang.IllegalAccessError: class net.minecraft.class_1309 tried to access private field virtuoel.pehkui.api.PehkuiConfig.DATA (net.minecraft.class_1309 and virtuoel.peh
kui.api.PehkuiConfig are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @1af2d44a)
        at net.minecraft.class_1309.revertScale(class_1309.java:6359) ~[intermediary-server.jar:?]
        at net.minecraft.class_1309.handler$zjh000$tryUseTotem(class_1309.java:6424) ~[intermediary-server.jar:?]
        at net.minecraft.class_1309.method_6095(class_1309.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_1309.method_5643(class_1309.java:1101) ~[intermediary-server.jar:?]
        at net.minecraft.class_1657.method_5643(class_1657.java:914) ~[intermediary-server.jar:?]
        at net.minecraft.class_3222.method_5643(class_3222.java:631) ~[intermediary-server.jar:?]
        at net.minecraft.class_1657.method_7324(class_1657.java:1234) ~[intermediary-server.jar:?]
        at net.minecraft.class_3222.method_7324(class_3222.java:1396) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12062(class_3244.java:1314) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824.method_12251(class_2824.java:74) ~[intermediary-server.jar:?]
        at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[21:08:13] [Server thread/ERROR]: This crash report has been saved to: /home/minecraft/minecraft-fabric/./crash-reports/crash-2021-04-28_21.08.13-server.txt
</code>
</pre>
</details>
